### ISSUE TITLE
ChoiceGroup: Change size and background color

### ISSUE THREAD

**Issue by MarkStokes-outlook** [OfficeDev/office-ui-fabric-core#1001]
Does anyone have any examples of how to change the size of the ChoiceGroup (the example using icons)? and also the background colour of the boxes?

I would like to have the boxes sit in two rows of three on an ms-u-lg5 grid box and colour code each of the items by changing the background colours.

TIA

**Comment by mikewheaton** [comment]
Fabric Core doesn't have the ChoiceGroup component. If you open an issue on [Fabric JS](github.com/OfficeDev/office-ui-fabric-js) or [Fabric React](github.com/OfficeDev/office-ui-fabric-react) (whichever you're using) they'll be able to answer your question.
