### ISSUE TITLE
Documentation: Update website documentation with new class names for v1.4.0

### ISSUE THREAD

**Issue by chadradams** [OfficeDev/office-ui-fabric-core#1003]
The CSS class names on the website documentation is out of date for v1.4.0.

**Example**:
```
<!-- Incorrect as found on https://dev.office.com/fabric#/styles/layout -->
<div class="ms-Grid-col ms-sm6 ms-md4 ms-lg2">A</div>

<!-- Correct-->
<div class="ms-Grid-col ms-u-sm6 ms-u-md4 ms-u-lg2">A</div>
```

**Comment by Jahnp** [comment]
Hey @chadradams, thanks! This is one of a few known documentation issues we'll be addressing very soon--we're working on a bunch of updates that should be rolling out over the next month or so. Though the code for the website is in the [Fabric-React](https://github.com/OfficeDev/office-ui-fabric-react) repo, I'll keep this issue open here since it concerns Fabric Core's grid class names.

**Comment by Jahnp** [comment]
Ah--I think I misunderstood this issue the first time through. The class names you list as "incorrect" are actually correct as of Fabric Core 6.0. What version are you using @chadradams? And, just to be clear, is this issue meant for Fabric Core (vs Fabric React)?

**Comment by chadradams** [comment]
This is Fabric Core v1.4.0 is what I'm using.  Is there a v6.0 css library, somewhere that I missed?

**Comment by Jahnp** [comment]
Fabric Core's latest version is [7.2.0](https://github.com/OfficeDev/office-ui-fabric-core/releases/tag/7.2.0)--you can see the releases here: https://github.com/OfficeDev/office-ui-fabric-core/releases

**Comment by chadradams** [comment]
I think this is where I got mixed up.  The Getting Started page had v1.2.0 for it's URL links.  Those should be updated.

https://dev.office.com/fabric#/get-started

Thanks Jahnp!

**Comment by Jahnp** [comment]
Sorry for the confusion! This is a [known issue](https://github.com/OfficeDev/office-ui-fabric-react/issues/2325) that's logged in the Fabric-React repo (where the website's source is located).

We know that the docs site in general needs some love--we're starting a big push on fixing the site (bugs, documentation, visualizations, etc.), so expect to see lots of changes here over the next few months.

**Comment by chadradams** [comment]
Excellent, this should help some of the icon issues I was seeing then.  Thanks again!
