### ISSUE TITLE
TextField required:  Property "required" does not exist

### ISSUE THREAD

**Issue by LarsLiden** [OfficeDev/office-ui-fabric-core#1005]
Following the example in the documentation (see below) and getting the error shown above

<TextField
            required={ true }
            onChanged={this.contentChanged.bind(this)}
            label="Payload"
            placeholder="Payload..." />

**Comment by Jahnp** [comment]
Hey @LarsLiden, is this meant for Fabric Core or Fabric React? If the latter, would you mind opening this issue there? https://github.com/OfficeDev/office-ui-fabric-react

**Comment by LarsLiden** [comment]
will do.  Thx!

**Comment by LarsLiden** [comment]
https://github.com/OfficeDev/office-ui-fabric-react/issues/2396
