### ISSUE TITLE
Contextual Menu icons in Fabric 4.26.0

### ISSUE THREAD

**Issue by ravalibusetty1991** [OfficeDev/office-ui-fabric-core#1006]
The icons are not appearing in the contextual menu after I updated to 4.26.0. Is there any change I should be vary of?

**Comment by Jahnp** [comment]
Hey @ravalibusetty1991, sorry for the delay here. It looks like this is related to [Fabric-React](https://github.com/OfficeDev/office-ui-fabric-react), not Fabric-Core. If this still repros for you with the latest release ([4.31.0](https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/office-ui-fabric-react_v4.31.0) as of this writing), would you mind opening this issue in that repo? I'll go ahead and close this in the meantime. Thanks!
