### ISSUE TITLE
Planner Icon does not display anything

### ISSUE THREAD

**Issue by ericnnguyen** [OfficeDev/office-ui-fabric-core#1009]
Hi, I am Eric from United Dev Portal team. When i use 
`<i class="ms-Icon ms-Icon--Planner c-heading-1" aria-label="Planner"></i>`

An icon is not being displayed. Is there an issue going on with this particular icon?

**Comment by mikewheaton** [comment]
Hi @ericnnguyen, I believe the icon name you're looking for is "PlannerLogo". Here is a CodePen showing that icon in use: https://codepen.io/mikewheaton/pen/mMpQdJ
