### ISSUE TITLE
Some icons are not showing up

### ISSUE THREAD

**Issue by BKLee-MS** [OfficeDev/office-ui-fabric-core#1012]
&lt;i className="ms-Icon ms-Icon--NavigateBack" aria-hidden="true"/&gt; does NOT show the icon.
&lt;i className="ms-Icon ms-Icon--Warning" aria-hidden="true"/&gt; does show the icon.
Same thing for some other icons. What's wrong?

**Comment by Jahnp** [comment]
Hey @BKLee-MS, which version of Fabric Core are you using? I notice you're using `className` to add the icon names--are you using [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react/), or Fabric Core directly?

**Comment by Jahnp** [comment]
For what it's worth, I'm able to get both to render using Fabric Core 7.2.0. Here's a CodePen to illustrate: https://codepen.io/jahnp/pen/prKxox

**Comment by Danny-Engelman** [comment]
``NavigateBack`` was added in 7.1.0
