### ISSUE TITLE
Need examples/samples linke/folder of websites using the UI Fabric

### ISSUE THREAD

**Issue by gregdegruy** [OfficeDev/office-ui-fabric-core#1013]

**Comment by mikewheaton** [comment]
This could be a good request for the [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react) project, which includes the documentation website. Could you open it there?

**Comment by gregdegruy** [comment]
Opened here > https://github.com/OfficeDev/office-ui-fabric-react/issues/2673
