### ISSUE TITLE
NPM office-ui-fabric or office-ui-fabric-core?

### ISSUE THREAD

**Issue by sureshjoshi** [OfficeDev/office-ui-fabric-core#1016]
I just discovered I was using an old version of Fabric because I was only pulling down office-ui-fabric-js, but then I discovered two projects (fabric 2.6.3) and (fabric-core 7.2.0) on NPM, with no real knowledge of when to use which one.

When I checked the releases for this project, I saw that those two are intertwined over the past few months (with fabric 2.6.3 being released 7 months ago, but seeing a 6.0.0 and a 6.0.1 release surrounding it).

In my package.json, which ones should I be using?

    "office-ui-fabric": "^2.6.3",
    "office-ui-fabric-core": "^7.2.0",
    "office-ui-fabric-js": "^1.4.0",

**Comment by mikewheaton** [comment]
The Office UI Fabric project has been deprecated. It was split out into Office UI Fabric Core and Office UI Fabric JS. So you should remove `office-ui-fabric` from your package.json. Sorry for the confusion here!
