### ISSUE TITLE
Which CSS should I use for Fabric JS

### ISSUE THREAD

**Issue by William-Au-Yeung** [OfficeDev/office-ui-fabric-core#1020]
My project is using Office UI Fabric JS instead of React. Which css file should my site link?

Option A: 
https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/css/fabric.min.css
https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/css/fabric.components.min.css

or Option B:
https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/7.2.0/css/fabric.min.css

and fabric.components.min.css does not exist in 7.2.0?

**Comment by Danny-Engelman** [comment]
option B should be:
https://spoprod-a.akamaihd.net/files/fabric/office-ui-fabric-core/7.2.0/css/fabric.min.css

**Comment by mikewheaton** [comment]
Please post this in the [Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js) project.
