### ISSUE TITLE
Lack of example to use PeoplePicker (Fabric JS)

### ISSUE THREAD

**Issue by William-Au-Yeung** [OfficeDev/office-ui-fabric-core#1022]
The example page has no information about how to add the functionality for the search button nor any description how to read the selected people.

https://dev.office.com/fabric-js/Components/PeoplePicker/PeoplePicker.html

Can anyone help me?

**Comment by mikewheaton** [comment]
Please post this in the [Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js) project.
