### ISSUE TITLE
After v8.0.0, ms-textAlignCenter is broken

### ISSUE THREAD

**Issue by austin-best** [OfficeDev/office-ui-fabric-core#1037]
The utility class `ms-textAlignCenter` sets `text-align:right` in dir='ltr' and `text-align: left`; in dir='rtl':

```
[dir='ltr'] .ms-textAlignCenter {
  text-align: right;
}

[dir='rtl'] .ms-textAlignCenter {
  text-align: left;
}

[dir='ltr'] .ms-textAlignRight {
  text-align: right;
}

[dir='rtl'] .ms-textAlignRight {
  text-align: left;
}
```

**Comment by mikewheaton** [comment]
Thanks for reporting this, @austin-best. A fix has been made and a new version of Fabric Core will be released today.
