### ISSUE TITLE
Icon request: CircleMinus/CircleSubtraction

### ISSUE THREAD

**Issue by Leif-Frederiksen** [OfficeDev/office-ui-fabric-core#1038]
Hi, I see that we have CirclePlus and CircleAddition, and I would expect to find CircleMinus/CircleSubtraction as well - I want to use them for collapsing/expanding tree nodes, and find the use of chevrons to be too ambiguous to users.

Regards
Leif

**Comment by mikewheaton** [comment]
Hi @Leif-Frederiksen, I just checked the master icon set that our icons are pulled from and unfortunately there's no CircleMinus or CircleSubtraction icon available.

While not in circles, you could consider these options:

![image](https://user-images.githubusercontent.com/1382445/32617104-f567dff0-c528-11e7-941c-f235ed232f14.png)
![image](https://user-images.githubusercontent.com/1382445/32617093-ef25e1a0-c528-11e7-82d9-a847e895eb10.png)

Or you could use CSS to draw a circle around these:
![image](https://user-images.githubusercontent.com/1382445/32617165-19e37330-c529-11e7-991b-1c5262de1f6c.png)
![image](https://user-images.githubusercontent.com/1382445/32617163-14ff7f80-c529-11e7-9c7a-8b8cd6aa24fb.png)
