### ISSUE TITLE
Since v8.0.0 there is no more float:left on .ms-Grid-col , thus no Grid layout

### ISSUE THREAD

**Issue by Danny-Engelman** [OfficeDev/office-ui-fabric-core#1044]
See: https://365csi.nl/toolkit/iconator/index.html
and switch to Core 8.0.0, 8.1.0 or 9.0.0 
grid layout is gone

**Comment by mikewheaton** [comment]
Have you added `dir="ltr"` to the page?

**Comment by Danny-Engelman** [comment]
You are correct ``<html dir="ltr">`` makes it work again (as stated in 8.0.0 Release Notes)

I skipped some versions and upgraded from 7.3.0 to 9.0.0
and must be one of the few who do not read all Release notes
