### ISSUE TITLE
Donwload of language pack not working

### ISSUE THREAD

**Issue by martinandersen3d** [OfficeDev/office-ui-fabric-core#1045]
The language pack for Office 2016, in the language "Danish" **download link doesnt work.** 

https://support.office.com/da-dk/article/Language-Accessory-Pack-til-Office-82ee1236-0f9a-45ee-9c72-05b026ee809f?ui=da-DK&rs=da-DK&ad=DK#ID0EAACAAA=2016

Sorry guys.. dont know where to report this issue. Hope someone will redirect this to the right person.

**Comment by mikewheaton** [comment]
I'm not sure who to contact about this error. Maybe try the 'Connect with an expert' option at the bottom of that page?
