### ISSUE TITLE
Add support for Selawik Bold

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#1054]
Now that we support Segoe UI Bold (see PR #1052), we should also add support for Selawik Bold. That font file can be found in the ZIP here: https://github.com/Microsoft/Selawik/releases

**Comment by lynamemi** [comment]
If I'm understanding the code correctly, now that selawik-bold is on the cdn, Fabric Core should be able to correctly use selawik-bold if the `ms-Fabric--selawik` class is used on the wrapper? Thus no additions needed to this repo?

**Comment by mikewheaton** [comment]
That went smoother than expected! Here's a [pen showing Selawik in use](https://codepen.io/mikewheaton/pen/vWLJpr).

Network requests:

![image](https://user-images.githubusercontent.com/1382445/32350334-51c7604c-bfd7-11e7-96ec-c5d8b3fda7fb.png)

How it looks:
![image](https://user-images.githubusercontent.com/1382445/32350343-5adaba80-bfd7-11e7-9026-0b70acc885da.png)

**Comment by lynamemi** [comment]
Hooray! So smooth. I need to get more in the habit of using codepen 😄
