### ISSUE TITLE
Iphone 8 mobile menu redraw issue

### ISSUE THREAD

**Issue by donhackman** [OfficeDev/office-ui-fabric-core#1056]
Taping a submenu will redraw it rather than return to the previous menu.

**Comment by mikewheaton** [comment]
Fabric Core doesn't contain any interactive components – maybe you meant to file this issue under [Fabric React](https://github.com/officeDev/office-ui-fabric-react)?

**Comment by donhackman** [comment]
Thanks Mike. I will file it there.
