### ISSUE TITLE
DetailList and List should support fetching data on need basis

### ISSUE THREAD

**Issue by hesawant** [OfficeDev/office-ui-fabric-core#1058]
Currently `DatailList` and `List` both support virtualization of DOM by rendering only those rows that are immediately visible. But it requires all the list items be provided before hand.

But in case the list to be displayed has large number items, say in the range of 30K - 50K then its a problem because fetching that many items over n/w takes time. 

A possible workaround for this is to fetch items in parts and keep updating the `items` props passed but this creates a problem for accessibility. The list reads out a number that is size of `items` props at a given time and this number keeps updating till all the items are fetched, thus confusing the user.

Here is something that I am hoping to have:
1. Make `items` props optional.
2. Add another prop `count` that indicates the total number of items in list.
3. A callback function that takes the start index of item and count of items to fetch from start index.
 And expects a Promise as return value that provides requested items.
4. While the promise is still unresolved the list can show placeholder ghost rows, either default or custom provided by user.

**Comment by mikewheaton** [comment]
Hi @hesawant, looks like you meant to file this in the [Fabric React issues](https://github.com/OfficeDev/office-ui-fabric-react/issues). Could you please report it there?

**Comment by hesawant** [comment]
Sorry my bad
