### ISSUE TITLE
Is't possible to use Fabric with javascript only without AngularJS and React?

### ISSUE THREAD

**Issue by biapar** [OfficeDev/office-ui-fabric-core#1062]
Is't possible to use Fabric with javascript only without AngularJS and React?

**Comment by mikewheaton** [comment]
You may want to consider the [Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js) project, although this does not receive the regular updates that [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react) does at this time.
