### ISSUE TITLE
Add documentation for ms-Fabric wrapper class to Fabric Core's "Get Started" section

### ISSUE THREAD

**Issue by Jahnp** [OfficeDev/office-ui-fabric-core#1064]
The "Get started with Fabric Core" section of the Fabric website includes a code sample that uses Fabric Core typography classes, but does not demonstrate the `ms-Fabric` wrapper class, which is necessary to set the `font-family` for the section where those classes are used.

Here is the section in question:
![image](https://user-images.githubusercontent.com/307118/32865613-b37aba96-ca18-11e7-941f-46ec921f5122.png)

Here is what that code should look like:

```html
<!-- ms-Fabric sets the font-family for all Fabric typography classes used in the element it's added to -->
<div class="ms-Fabric">
  <span class="ms-font-su ms-fontColor-themePrimary">Big blue text</span>
</div>
```

**Comment by Danny-Engelman** [comment]
May I suggest a comment to add it on the body, so developers do **not** put in on every wrapping element

```
<body class="ms-Fabric">
```

**Comment by Jahnp** [comment]
@Danny-Engelman that's a fair suggestion and probably reflects the largest majority of developer scenarios. I'll go ahead and do that when I update this section on the site (hopefully making the code change today). Thanks for the reminder!

For some context around why I actually didn't want to use `body` initially: Internally within Microsoft, there are many many cases where product teams need to onboard an existing application to Fabric/Fabric React. The `ms-Fabric` class allows those teams to incrementally "Fabricize" portions of their app, e.g. a sidebar or header portion, without making sweeping global changes. Making changes to how fonts are loaded & applied can be quite disruptive to a complex app. 

That said, I get that for a large percentage of developers using Fabric Core, that scenario probably won't be as common :) So I'll just keep it simple and use `body` as you suggest.

**Comment by mikewheaton** [comment]
I've opened an issue in the Fabric React repo (where the documentation lives) and assigned it to @lynamemi, as she's been improving this documentation recently. :)
