### ISSUE TITLE
Wrong Icons

### ISSUE THREAD

**Issue by AcciolyDSI** [OfficeDev/office-ui-fabric-core#1066]
Hello, version 9.2.0 does not show some icons, they do exist but are not recognized, see here https://developer.microsoft.com/en-us/fabric#/styles/icons

: (

**Comment by Danny-Engelman** [comment]
At the moment (nov 21 13:00) that sites still uses 9.0.0

![](https://i.imgur.com/lM7xMja.jpg)

**Comment by Jahnp** [comment]
That's correct, good catch. We'll be updating the iconography soon--I'd expect a fix out within the next week or so (barring Thanksgiving interruptions).

**Comment by AcciolyDSI** [comment]
Oh Jahnp, thank you, : )

**Comment by lynamemi** [comment]
Made a fix on the website side of things:
https://github.com/OfficeDev/office-ui-fabric-react/pull/3446

**Comment by mikewheaton** [comment]
Closing this as it's an issue of the website being out-of-date, and not something to fix in Fabric Core itself.
