### ISSUE TITLE
wordpress problem

### ISSUE THREAD

**Issue by cmk128** [OfficeDev/office-ui-fabric-core#1077]
Hi, i put the commandBar example, the menu seem have a wrong offset.

This page http://www.quantr.hk/index.php/test/ will embed http://www.quantr.hk/wp-content/plugins/sharepoint-doclib/public/shortcode.html , as you can see the second link work perfectly, but the first link have a wrong y-offset

<img width="1445" alt="screen shot 2017-12-12 at 3 10 16 pm" src="https://user-images.githubusercontent.com/34470546/33871852-49d0943e-df4f-11e7-80b6-b6ae47809f4b.png">

**Comment by mikewheaton** [comment]
Fabric Core doesn't have components. Did you mean to open this issue on [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react)?
