### ISSUE TITLE
File Upload with Drag and drop

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-ui-fabric-core#1078]
Can you please add component for drag and drop file upload control?

**Comment by Jahnp** [comment]
Hi @russgove, this issue queue is for Fabric Core, which doesn't have UI components--just design language fundamentals (type, colors, icons, animations, etc.) I assume this is meant for [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react/)--can you open this in that repo? Thanks!
