### ISSUE TITLE
grid not working

### ISSUE THREAD

**Issue by cmk128** [OfficeDev/office-ui-fabric-core#1079]
I am following the example on office-ui-fabric, but doesn't work. It seems there is a different between office-ui-fabric and office-ui-fabric-core. Please help
```
<html>
        <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/9.2.0/css/fabric.min.css">
<body class="ms-fabric">
<span class="ms-font-su ms-fontColor-themePrimary">Big blue text</span>

<div class="ms-Grid">
  <div class="ms-Grid-row">
    <div class="ms-Grid-col ms-sm6 ms-md4 ms-lg2">A</div>
    <div class="ms-Grid-col ms-sm6 ms-md8 ms-lg10">B</div>
  </div>
  <div class="ms-Grid-row">
        <div class="ms-Grid-col ms-sm4 ms-smPush8">First in code</div>
        <div class="ms-Grid-col ms-sm8 ms-smPull4">Second in code</div>
  </div>
</div>

</body> 
</html>
```

**Comment by Danny-Engelman** [comment]
See same previous issue: https://github.com/OfficeDev/office-ui-fabric-core/issues/1044

This was a breaking change in 8.0.0

You need to add a ``dir`` attribute

**Comment by cmk128** [comment]
you are right, it works now. But isn't this setting too overbearing？I am using it in wordpress, and no api can add "dir"
