### ISSUE TITLE
Message bar style - 4 inconsistencies

### ISSUE THREAD

**Issue by javenu** [OfficeDev/office-ui-fabric-core#1084]
The message bars, as portrayed on the [Fabric site](https://developer.microsoft.com/en-us/fabric), are inconsistent in 4 areas:

**Height** - the single line Info bar is 44px, yet the single line Error and Blocked bars are 32px
**Icons** - the Blocked and Error icons are larger than the rest of the icons. The success circle is larger than the info circle.
**Indent** - not only are they larger, but the Error and Blocked icons are indented by 4px, which pushes the message over as well
**Caps** - half of the messages start with uppercase Lorem, the other start with lowercase lorem. What is the standard?

When stacking the message bars in the UI, these anomalies stand out.
Were the Error and Blocked bars created w/o aligning to the existing bars?

As a designer, its difficult to follow the style when it isn't consistent. :)

**Comment by mikewheaton** [comment]
Please open this issue in the [Fabric React repo](https://github.com/OfficeDev/office-ui-fabric-react), as the [MessageBar](https://developer.microsoft.com/en-us/fabric#/components/messagebar) is part of the React components set. Thanks!
