### ISSUE TITLE
Add a Settings Fill/Solid icon

### ISSUE THREAD

**Issue by nero120** [OfficeDev/office-ui-fabric-core#1085]
Could you please add a fill/solid for the Settings icon? The contrast of the filled-in icon would make it much more visible when using as an IconButton displayed on top of images/backgrounds:

![image](https://user-images.githubusercontent.com/4236238/34525924-85768156-f098-11e7-9d15-c3de736cab9c.png)

**Comment by nero120** [comment]
Also for the Delete icon if it's not too much trouble! 😄

**Comment by Jahnp** [comment]
Hi @nero120, I can forward this request along to the team that designs the monoline icons, but I doubt they'll want to support this as the MDL2 design language generally favors the stroke-based icons we have now.

Generally, when we want to overlay icons on top of more visually-complex backgrounds--or when we just want an icon to stand out--we would recommend leaving them white/reversed and putting them in a darker box that will stand out. You can see an example of this in the authoring experience of a SharePoint page, when I want to modify properties of the header section:

![image](https://user-images.githubusercontent.com/307118/34629317-8da3d862-f21c-11e7-9290-4475d7a8da1f.png)

In the meantime, I'll go ahead and close this, but please let me know if this doesn't resolve your issue.
