### ISSUE TITLE
Nav: Not keyboard accessible

### ISSUE THREAD

**Issue by tx4x** [OfficeDev/office-ui-fabric-core#1095]
Hi,
are there any plans to add keyboard support to `<Nav> and <CommandBar>` ? If not, do you have some pointers how to add this myself ? I am not sure about the other components since I am a newbie to fabric-ui but I guess I need a general solution to add this everywhere. 

Thanks in advance!

**Comment by mikewheaton** [comment]
Sorry for the confusion here, but the repo you're looking for is [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react). Please post your question there and someone should be able to assist.
