### ISSUE TITLE
neutralQuaternary and neutralQuaternaryAlt missing from Colors

### ISSUE THREAD

**Issue by lynamemi** [OfficeDev/office-ui-fabric-core#1102]
In FabricReact we noticed that these colors were missing from the website documentation page. Upon adding them (https://github.com/OfficeDev/office-ui-fabric-react/pull/4188) It appears that they are also missing here.

**Comment by mikewheaton** [comment]
Good catch. We have the [variables](https://github.com/OfficeDev/office-ui-fabric-core/blob/master/src/sass/variables/_Color.Variables.scss#L23) defined, but no mixins or classes.

**Comment by lynamemi** [comment]
I'm close to a PR!

**Comment by mikewheaton** [comment]
@lynamemi Thanks! I've assigned this bug to you. 😄
