### ISSUE TITLE
Dropdowns not showing in WordAddIn

### ISSUE THREAD

**Issue by sebastianbouckaert** [OfficeDev/office-ui-fabric-core#1110]
Very simple straight forward out-of-the-box project from VisualStudio.
![fabricuidropdown](https://user-images.githubusercontent.com/20515102/37896213-d29b24f8-30d2-11e8-8c56-06ef4b7a6816.PNG)

Results in:

![fabricuidropdown2](https://user-images.githubusercontent.com/20515102/37896270-f4f6e294-30d2-11e8-9f33-4cb6a070f33f.PNG)

**Comment by mikewheaton** [comment]
@sebastianbouckaert It looks like these are [Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js) components. Could you open an issue there?
