### ISSUE TITLE
Office UI Fabric - File input component

### ISSUE THREAD

**Issue by mubash7** [OfficeDev/office-ui-fabric-core#1118]
I am building an upload document feature in SharePoint with some specific requirement. I need a component for file input so that user can select a document from local machine to upload in sharepoint. #123

**Comment by mikewheaton** [comment]
Hi @mubash7, could you open this request in the [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react) repo? Thanks!

**Comment by mubash7** [comment]
@KevinTCoughlin  it will not as the files will be from the local machine.

**Comment by mubash7** [comment]
@mikewheaton will do. Thanks.
