### ISSUE TITLE
Can ms-Grid-row span?

### ISSUE THREAD

**Issue by peterremote1980** [OfficeDev/office-ui-fabric-core#1122]
Can ms-Grid-row span? thanks

**Comment by mikewheaton** [comment]
Sorry, I'm not sure what you mean. Could you include an illustration to show what you're hoping to achieve?

**Comment by peterremote1980** [comment]
i have two rows with two columns, but i want to span the first columns into one.

like this https://i.stack.imgur.com/m741R.png

Thanks
From Peter

**Comment by mikewheaton** [comment]
The best way to achieve that layout is by nesting grids. See [this StackOverflow question](https://stackoverflow.com/questions/16351404/bootstrap-combining-rows-rowspan) for how to achieve a similar layout using Bootstrap's grid, which is very similar to ours.
