### ISSUE TITLE
[enhancement] slider value label 

### ISSUE THREAD

**Issue by ttseattle** [OfficeDev/office-ui-fabric-core#1124]
Right now, `showValue` in the Slider component allows the numerical value to be shown. However, I want the Slider to show not just **5**, but **5 _seconds_**. Can there be another parameter that allows you to customize the slider value label?

**Comment by mikewheaton** [comment]
Hi @ttseattle, I think you may be looking for the [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react) repo.
