### ISSUE TITLE
ms-Dropdown-title overflow

### ISSUE THREAD

**Issue by basovic88** [OfficeDev/office-ui-fabric-core#1126]
Suppose that I have:

```
<div style="{ display: flex }">
   <div style="{ width: 32px }"/>
   <div style="{ flex: 1 1 auto }">
      <!-- ms-Dropdown here -->
    </div>
</div>
```

Now, the 'ms-Dropdown-title' element overflows, when I shrink the screen. Meaning I get a scrollbar instead of the 'ellipsis'.

**Possible fix**: When I set the 'white-space' attribute to 'normal' instead of 'nowrap', all is well!

(With firefox 60.0.2 and office-ui-fabric-react)

**Comment by mikewheaton** [comment]
Hi @basovic88, could you please open this issue in the [Fabric React repo](https://github.com/OfficeDev/office-ui-fabric-react/issues)? Thanks!
