### ISSUE TITLE
Implement Fabric as Web components

### ISSUE THREAD

**Issue by RaulRG** [OfficeDev/office-ui-fabric-core#1131]
My company is using Angular for web development. Fabric looks great, but you seem to prefer React. If you implemented your components as web components they could be consumed easily by both React and Angular (and a ton of other frameworks).

I think web components is the way to go for anything UI related. You would just implement them and not need to write the wrapper for React.

Look at [https://stenciljs.com/](url) for a cool system for creating components with Typescript.

**Comment by mikewheaton** [comment]
Thanks for the suggestion, @RaulRG. The best place to post this would be in the [Fabric React repo](https://github.com/OfficeDev/office-ui-fabric-react) as that's where the components are.
