### ISSUE TITLE
Shimmer is absent in package 1.5.1

### ISSUE THREAD

**Issue by Krak86** [OfficeDev/office-ui-fabric-core#1146]
I am building the SPFx webpart (1.5.1 version) using yeoman, and it deploys the same fabric core version automatically (1.5.1).
I chose the React framework. So in project's `package.json` I see `"@microsoft/sp-office-ui-fabric-core": "1.5.1"` only, no direct `office-ui-fabric-react` packages.

Usually when I am importing a Fabric components I am using the next path, for instance:
`import { Spinner, SpinnerSize } from 'office-ui-fabric-react/lib/Spinner';`
`import { Pivot, PivotItem } from 'office-ui-fabric-react/lib/Pivot';`

When I am trying to import Shimmer component:
`import { Shimmer } from 'office-ui-fabric-react/lib/Shimmer';`
the IDE says "Cannot find module 'office-ui-fabric-react/lib/Shimmer'".

I checked the `node_modules` folder and also didn't find the Shimmer component there.

How can I handle it? Is it removerd from 1.5.1 version or should I add it separately somehow?

**Comment by Vitalius1** [comment]
Shimmer is only part of the `office-ui-fabric-react` package and never was intended to get into the `core`. What does `@microsoft/sp-office-ui-fabric-core": "1.5.1"` include?

**Comment by Krak86** [comment]
> I checked the node_modules folder and also didn't find the Shimmer component there.
Indeed I did, but nothing there.
