### ISSUE TITLE
Installation of office-ui-fabric-core by NPM failed

### ISSUE THREAD

**Issue by mmofidi** [OfficeDev/office-ui-fabric-core#1147]
Below you can see the screen shot of error
![npmfabric-core-error](https://user-images.githubusercontent.com/10815466/47236196-5e4f7700-d3a9-11e8-8c7f-9230c9345a28.JPG)

**Comment by mikewheaton** [comment]
It looks like you're getting this error happens uninstalling Fabric Core. Try some of the suggestions here: https://stackoverflow.com/questions/46541371/npm-err-refusing-to-delete-code-eexist
