### ISSUE TITLE
TimeEntry icon does not display

### ISSUE THREAD

**Issue by asadullah313** [OfficeDev/office-ui-fabric-core#1148]
Hi

The TimeEntry icon does not work. All other icons seem to work fine.

`<i class="ms-Icon ms-Icon--TimeEntry aria-hidden="true"></i>
`

However, I have noticed that it works when used in the Tiles Web Part:
https://github.com/SharePoint/sp-starter-kit/tree/master/solution/src/webparts/tiles

**Comment by mikewheaton** [comment]
Which version of Fabric Core are you using? I'm not able to repro this: https://codesandbox.io/s/8xp924n2y9

**Comment by Jahnp** [comment]
Hi @asadullah313 , I'm going to go ahead and close this as I cannot repro the issue either. Please let me know if you're still having issues with this icon and I'm happy to re-open the issue and take a closer look.
