### ISSUE TITLE
How to restyle DetailsList

### ISSUE THREAD

**Issue by DiandianWendy** [OfficeDev/office-ui-fabric-core#1151]
I am using DetailsList component, but find that it is hard to restyle it, as styles property is not available . Currently I directly override some ms-* class in css file as a work around. Is there any other solutions?

**Comment by mikewheaton** [comment]
Hi @DiandianWendy, the GitHub project you want to open this issue on is [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react). Thanks!

**Comment by DiandianWendy** [comment]
Hi Mike,
OK. I will move it there.

Thanks,
Wendy
