### ISSUE TITLE
console log errors for browser pipe aria. 

### ISSUE THREAD

**Issue by paigeflourin** [OfficeDev/office-ui-fabric-core#1152]
Not sure what this error is but i have been noticing a lot of this being logged when i run my SPFX app. it doesnt really affect my application and its features (none that i know of) but it gets really annoying when i am debugging. 

Can i get help understanding what this issue is? not sure how to resolve this.

POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=ACT-Web-JS-2.9.0&x-apikey=28f004ff2be44e8997a6f113043d583d-3f663b9a-4911-45b4-be6d-e450ca91e808-7336 net::ERR_BLOCKED_BY_CLIENT

![image](https://user-images.githubusercontent.com/6951524/48310918-db999080-e5d1-11e8-80e3-4432a3f95686.png)

**Comment by mikewheaton** [comment]
Are you running an ad blocker? It looks like this could be a SharePoint telemetry system that is being blocked. Try disabling your ad blocker and see if the warnings persist.

This project (Fabric Core) should not be making any requests to servers as it doesn't include JavaScript, so I'm going to close this issue.
