### ISSUE TITLE
Component code demon for common developer

### ISSUE THREAD

**Issue by lanzhiheng** [OfficeDev/office-ui-fabric-core#1155]
This is a very cool UI library, thank you for sharing it.

But I see all the code example of the component is React 

![image](https://user-images.githubusercontent.com/8858472/50538935-1623b080-0bb3-11e9-8489-aaf6dfca9181.png)

I can not find the simple component's html code in the document, It is not easy for me to copy & paste the code to my exists project. Can you provide the link for it ?

**Comment by Danny-Engelman** [comment]
Have you seen: https://developer.microsoft.com/en-us/fabric-js

**Comment by lanzhiheng** [comment]
@Danny-Engelman Thank you, that is what I need. I am sorry that I can not find this link in the UI relevant page https://developer.microsoft.com/en-us/fabric. I think that may be a good idea to add it here .

![image](https://user-images.githubusercontent.com/8858472/50539127-c5618700-0bb5-11e9-9e32-1ba8a0cce419.png)
