### ISSUE TITLE
Color-contrast issue from disabled toggle label.

### ISSUE THREAD

**Issue by mslonli** [OfficeDev/office-ui-fabric-core#1157]
How to repro: The 'Off' label has color-contrast issue.
`
<Toggle
defaultChecked={false}
disabled={true}
label="Disabled and unchecked"
onText="On"
offText="Off"
onFocus={() => console.log('onFocus called')}
onBlur={() => console.log('onBlur called')}
/>
`

**Comment by mikewheaton** [comment]
Hi @mslonli, could you report this in the [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react) project?
