### ISSUE TITLE
Help Icon Missing

### ISSUE THREAD

**Issue by scottkuhl** [OfficeDev/office-ui-fabric-core#1160]
I can get all the icons to work except the help icons.  (ms-Icon--Help and ms-Icon--HelpMirrored)  Those do not render at all.

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/9.6.1/css/fabric.min.css" />
    <title></title>
</head>
<body>

    <p>Help: <i class="ms-Icon ms-Icon--Help"></i></p>

    <p>Search: <i class="ms-Icon ms-Icon--Search"></i></p>

</body>
</html>
```

**Comment by mikewheaton** [comment]
Sorry for the trouble here; we need to update our documentation. I've opened [#7923](https://github.com/OfficeDev/office-ui-fabric-react/issues/7923) to fix this.

Many of our icons have a mirrored version for use with right-to-left (RTL) languages. The Help icon is one of them:

![image](https://user-images.githubusercontent.com/1382445/52428741-79a8d400-2ab7-11e9-87f6-8691fded7c9d.png)

To automatically choose the right icon, we look for the `dir` (direction) attribute. So to get this icon working you'll need to have `<body dir='ltr'>` set. Here's a [working example](https://codesandbox.io/s/xpl8nznq6q).
