### ISSUE TITLE
how can i use RTL version?

### ISSUE THREAD

**Issue by khoshroomahdi** [OfficeDev/office-ui-fabric-core#1178]

**Comment by Jahnp** [comment]
Hi @khoshroomahdi , all you need to is set the `dir` attribute to `rtl`. Here's a code snippet from the [Getting Started page](https://developer.microsoft.com/en-us/fabric#/get-started#fabric-core):
```html
<body class="ms-Fabric" dir="ltr">
  <span class="ms-font-su ms-fontColor-themePrimary">Big blue text</span>
</body>
```
