### ISSUE TITLE
missing CommentSolid in the Office UI Fabric Icons

### ISSUE THREAD

**Issue by rychlym** [OfficeDev/office-ui-fabric-core#1182]
Hello!
It seems to me to be highly convenient to add the Comment Solid icon to the Office UI Fabric Icons.
Customers often would like to see the count of likes and the count of comment in a blog post item. The solid variants of the icons would be suitable for that . The "Like" icon (and lot of other icons) already have its "solid" counterpart (the most near is the "Chat" icon)
The enclosed picture shows, what I mean...
![blog](https://user-images.githubusercontent.com/11144487/58230751-83d4a280-7d35-11e9-839d-8f4a0792e9e4.png)

Can you,please, provide the icon in the near future?
(Or at least, would you know which Unicode character could be reserved for it in the future?)

**Comment by Jahnp** [comment]
Hi @rychlym , thanks for reaching out! This is a super reasonable request. I'll reach out to the icons team and look into having this added.

**Comment by Jahnp** [comment]
Hi @rychlym , oops—I forgot to follow up here, apologies. So the good news is that I was able to get this icon added to the Fabric icons tool: https://aka.ms/uifabric-icons

So you can start using the icon now with custom subsets. We'll also plan an update to the base Fabric Core icon set.

**Comment by rychlym** [comment]
Hi @Jahnp, I have tried it and the new icon is present there now - thanks a lot!
