### ISSUE TITLE
fabric ui for blazor

### ISSUE THREAD

**Issue by khoshroomahdi** [OfficeDev/office-ui-fabric-core#1183]
please make a project for blazor

**Comment by bonebizz21** [comment]
Gucci

**Comment by Jahnp** [comment]
Hi @khoshroomahdi , while Blazor is an awesome project—and we think it's worth exploring integrations between it and Fabric—we don't have any current plans to share. Further, we would likely explore those in the context of Fabric React, which has a much more robust component story than Fabric Core does. I'm going to close this as it doesn't pertain to Fabric Core's charter. Thank you!
