### ISSUE TITLE
Is there panel style?

### ISSUE THREAD

**Issue by khoshroomahdi** [OfficeDev/office-ui-fabric-core#1187]

**Comment by Jahnp** [comment]
Hi @khoshroomahdi , while there are no raw CSS styles for Panels, there is a Panel component in Fabric React: https://developer.microsoft.com/en-us/fabric#/controls/web/panel

I'm going to close this out as Fabric Core does not include component styles today. [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react/) would be a better fit for that. Thank you!
