### ISSUE TITLE
Panel doesn't allow close on click outside panel when isBlocking prop is false

### ISSUE THREAD

**Issue by bansalrachita** [OfficeDev/office-ui-fabric-core#1201]
Panel should allow for close on click outside of panel if modal overlay is false.

Current:
The panel props `onOuterClick` doesn't take effect if the `isBlocking` is false.

Expected:
The panel props `onOuterClick` should be able to dismiss the panel even when `isBlocking` is false.

Reference code:
https://codepen.io/bansalrachita/pen/QWWRXXB

**Comment by Jahnp** [comment]
Hi @bansalrachita , apologies for the big delay. This looks like an issue for [office-ui-fabric-react](https://github.com/OfficeDev/office-ui-fabric-react/issues)—would you mind re-opening this there?

**Comment by bansalrachita** [comment]
@Jahnp 
Seems like it still exists. Re-opened this issue here:
https://github.com/OfficeDev/office-ui-fabric-core/issues/1201
