### ISSUE TITLE
Some icons missing while using CDN

### ISSUE THREAD

**Issue by hammerstrike** [OfficeDev/office-ui-fabric-core#1224]
I'm using core library CDN given in [documentation ](https://developer.microsoft.com/en-us/fluentui#/get-started/web#fabric-core)page.

> https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css

Trying to use icons but might be some (new) icons seems like not updated.
Below code not shows calendar icon with given CDN
`<span class="ms-Icon ms-Icon--Calendar"></span>`

**Comment by chendjouCaleb** [comment]
You can use the unicode of the icon like this.
`.ms-Icon--Calendar:before {
  content: '\E787'
}`

YOU can replace the missing css classes this way.
