### ISSUE TITLE
SVG for the icons 

### ISSUE THREAD

**Issue by SimranjitKaurMaan** [OfficeDev/office-ui-fabric-core#1239]
Is there any link to access SVG of the set of icons like Chat/Refresh?

We are trying to use the SVG/PNG of the icons available in https://uifabricicons.azurewebsites.net/. Our project needs the SVG of the generic icons.

Any help will be appreciated.

**Comment by SimranjitKaurMaan** [comment]
Thanks I got what i needed.

**Comment by bottbott** [comment]
Hi @SimranjitKaurMaan - could you share your solution for how you got the SVG icons?
