### ISSUE TITLE
Content grouping (Accordion)

### ISSUE THREAD

**Issue by git-sdavidpaul** [OfficeDev/office-ui-fabric-core#128]
Is there any components (current or upcoming) for grouping content? something like Accordion panels etc. or some other intuitive controls for grouping content under some common entities.

**Comment by ericthompson** [comment]
Looking into this!

**Comment by mikewheaton** [comment]
We're working on an accordion for use within a panel. It's not yet clear when this will be made available as a Fabric component.

**Comment by mikewheaton** [comment]
We've assigned this to a designer.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#30
