### ISSUE TITLE
Form components inconsistent spacing

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#306]
Form elements and labels have inconsistent spacing:
- Most labels have `padding: 5px 0`, except for the `.ms-Toggle-description`
- Dropdown has 10px of margin at the bottom, text box has 8px, toggle has 26px

![spacing](https://cloud.githubusercontent.com/assets/1382445/12736603/852f2aec-c906-11e5-810b-1be5e6d60a42.png)

See **[the repro on CodePen](http://codepen.io/mikewheaton/pen/gPjmad)**.

**Comment by mikewheaton** [comment]
**[Proposed fixes](http://codepen.io/mikewheaton/pen/EPpWNW)**.

**Comment by notandrew** [comment]
Adding needs-design since it's possible that the variable spacing is by design (it is in other projects)

**Comment by mikewheaton** [comment]
This has been assigned to a designer for review.

**Comment by mikewheaton** [comment]
We'll be addressing this issue in the next major release of Fabric, which will include an updated design language.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#31
