### ISSUE TITLE
DropDown: Initialize with a selected option

### ISSUE THREAD

**Issue by cut2run** [OfficeDev/office-ui-fabric-core#321]
Request:
I need to initialize Dropdown control with certain pre-selected value. The control doesn't looks like have documentation on how to properly do that.

Try and fail:
1. If control initialized first ` $('.ms-Dropdown').Dropdown();` and after select a value `$('#select_language').val('en-us').change();` nothing happen at all from UI point of view. Query back value from select and it will return proper "changed" value.
2. If set the value first and after initialize control as "Dropdown" the control appear with pre-selected value. This is good sign. When you click on dropdown to see the options, pre-selected option doesn't have "blue" highlights as it happen when you click on the option. Another thing I have to care of double initialization of control and this will lead to remove and re-insert it. This is not good at all.

Suggestion:
Would it be possible to have initialization with a value at any time with some method? At this point I assume control should look exactly the same as it would look when user choose an option from dropdown manually. As such: option preselected and when dropdown open the same option highlighted in the list.

Thanks.

**Comment by mikewheaton** [comment]
Our dropdown's JavaScript should absolutely support reading of the `selected` attribute from the underlying `option` elements. We're working on new JavaScript for each component (see [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md)) and we'll include this feature with the dropdown.

**Comment by cut2run** [comment]
Mike,

The control is looking sharp and I would like to use it, but ...

As I add more and more UI pieces into our add-in I believe the request I made is the necessity other than enhancement. This is basic control we are talking about, not like fancy request. The control has to have option to be pre-selected as checkbox or radio controls included into library. Otherwise it is unuseful when doesn't reflect to selected value.
You right, I am able to read selected value, but not set it in the way control display selection properly.
From says above I would like to ask you to review the request again to give more priority may be?

**Comment by SharePointOscar** [comment]
I am using v 2.6.1 and still can't seem to set the dropdown item selected property, any workarounds if this is still not supported for this component?  Thank you Gents!

**Comment by schott12521** [comment]
Oscar, make sure that you are initializing the dropdown AFTER setting the default value. In other words, set the default value first THEN initialize the ms-Dropdown, that works for me on 2.6.1

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#33
