### ISSUE TITLE
Remove line height from ms-Icon

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-core#354]
.ms-Icon has line-height: 1. Is there a reason for that? It seems like it should inherit line-height from the parent.

**Comment by mikewheaton** [comment]
I don't see any need for that – the icons should sit with whatever text they're contained within, so we should be inheriting line height.

**Comment by dzearing** [comment]
Cool, sounds good. Right now we end up explicitly overriding it in a number of places, so removing it would be ideal.

**Comment by mikewheaton** [comment]
We're going to push this change ahead to a future release. It's simple enough, but it could be a breaking change in cases where others have changed styles to accommodate the line height. We have more breaking changes coming to the icons soon and will bundle this change with those.

**Comment by mikewheaton** [comment]
Fixed by #758
