### ISSUE TITLE
Localization: Set font-family with ms-Fabric wrapper

### ISSUE THREAD

**Issue by kennywangjin** [OfficeDev/office-ui-fabric-core#382]
when I apply "lang='cn-ZHS'" to <html />, the whole page font family keeps segoe ui, while it should be Microsoft yahei.
Is it a bug or have I missed some steps? 
(I am trying as office ui fabric website shows.)
Thanks in advance.

**Comment by mikewheaton** [comment]
Could you take a look at this, @notandrew? Also, we should get a test/sample page set up so that we can quickly verify that the other font stacks are working.

**Comment by notandrew** [comment]
We have a typo.  We are using ch-ZHS instead of cn.  This should fix it for this release of Fabric.  I'll make a fix tonight so it point to cn-ZHS.  I just noticed other teams use zh-cn. I'll investigate which language codes we should be using.

**Comment by mikewheaton** [comment]
Would be great if we could use the [standard HTML ISO Language Codes](http://www.w3schools.com/tags/ref_language_codes.asp).

**Comment by notandrew** [comment]
Microsoft has its own lcid codes: https://msdn.microsoft.com/en-us/library/cc233982.aspx

**Comment by mikewheaton** [comment]
Interesting. Those are for Microsoft Windows though, do they make sense for a web product? We only use a tiny subset of that, and what we have maps more closely to the ISO 639-1 codes that the W3C recommends.

**Comment by mikewheaton** [comment]
Also, he said that he's using "cn-ZHS", exactly as we have it in our docs. Is that not what's in Fabric right now?

**Comment by notandrew** [comment]
Right, that's the typo, we have ch-ZHS in Fabric.

**Comment by mikewheaton** [comment]
Ah okay. @kennywangjin, could you try changing the `lang` attribute to "ch-ZHS" and confirm that it works for you?

**Comment by notandrew** [comment]
OneDrive uses the Microsoft lcid codes that I referenced above, but those match language/region instead of just language, which we're probably more interested in...

**Comment by kennywangjin** [comment]
@mikewheaton I was using "ch-ZHS", just as the fabric web's demo. Not working.

**Comment by mikewheaton** [comment]
Okay, I guess both cn-ZHS and ch-ZHS are not working for Kenny. We'll have to look into this and see if we can reproduce it.

**Comment by notandrew** [comment]
@kennywangjin Are you applying our font classes to the containers? Here's what the Fabric CSS looks like -- so any of these font classes should be applied:
*[lang='ch-ZHS'] .ms-font-mi,
*[lang='ch-ZHS'] .ms-font-xs,
*[lang='ch-ZHS'] .ms-font-s,
*[lang='ch-ZHS'] .ms-font-s-plus,
*[lang='ch-ZHS'] .ms-font-m,
*[lang='ch-ZHS'] .ms-font-m-plus,
*[lang='ch-ZHS'] .ms-font-l,
*[lang='ch-ZHS'] .ms-font-xl,
*[lang='ch-ZHS'] .ms-font-xxl,
*[lang='ch-ZHS'] .ms-font-su,
*[lang='ch-ZHS'] .ms-fontWeight-light,
*[lang='ch-ZHS'] .ms-fontWeight-light-hover:hover,
*[lang='ch-ZHS'] .ms-fontWeight-semilight,
*[lang='ch-ZHS'] .ms-fontWeight-semilight-hover:hover,
*[lang='ch-ZHS'] .ms-fontWeight-regular,
*[lang='ch-ZHS'] .ms-fontWeight-regular-hover:hover,
*[lang='ch-ZHS'] .ms-fontWeight-semibold,
*[lang='ch-ZHS'] .ms-fontWeight-semibold-hover:hover {
  font-family: 'Microsoft Yahei', Verdana, Simsun, 'Segoe UI', Tahoma, Arial, sans-serif;
}

**Comment by kennywangjin** [comment]
@mikewheaton Many HTML elements have been hard-coded "font-family", like table, dialog. It is impossible to apply general font family via lang="zh-CHS" mode.

**Comment by notandrew** [comment]
Oh, I see this too:
.ms-Breadcrumb-itemLink {
  color: #333333;
  font-family: 'Segoe UI Light WestEuropean', 'Segoe UI Light', 'Segoe UI', Tahoma, Arial, sans-serif;
  font-size: 21px;
  font-weight: normal;
....
}
src:
.ms-Breadcrumb-itemLink {
  @include ms-font-xl();
  display: inline-block;

We should definitely find a different way to do this since it breaks localization scenarios.  Maybe we apply the ms-font-xl class in markup instead of the SCSS.

**Comment by mikewheaton** [comment]
Agreed, we need to get the hard-coded font families out of the components. See issues #442 and #443 for related problems and a proposed solution.

**Comment by mikewheaton** [comment]
Reopening. Each of the components in [Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js) now uses the `ms-baseFont` mixin to set the font family. But we still don't override that base font depending on the language in use on the page. This is what we should use the `ms-Fabric` class for -- to set a base font for the entire page and then only change the weight within components. Still needs work.

**Comment by mikewheaton** [comment]
Related issue in Fabric React: [ms-Link font-family should "inherit"](https://github.com/OfficeDev/office-ui-fabric-react/issues/506)

**Comment by mikewheaton** [comment]
Another note here:

Currently the base font classes (such as `ms-font-m`) set `font-family` and `-webkit-font-smoothing`. Both of those properties should be set a single time in `ms-Fabric`, so that the base font classes set only a size and weight.

**Comment by notandrew** [comment]
looks good ;)
