### ISSUE TITLE
NavBar context menu alignment 

### ISSUE THREAD

**Issue by cut2run** [OfficeDev/office-ui-fabric-core#384]
When NavBar item ("ms-NavBar-item") has right alignment ("ms-NavBar-item--right") and context menu ("ms-NavBar-item--hasMenu") would it be appropriate to align this context menu to the right? Currently if context menu added its position will start from beginning of the NavBar item and will be out of screen boundaries that produce horizontal scroll bar. You probably can read style of NavBar item and if it has class "ms-NavBar-item--right" add context menu style "right:0px" to make menu appear aligned to the right window boundary. Screenshots before and after as follow ...

![image](https://cloud.githubusercontent.com/assets/17089974/13299993/dee002c0-db0b-11e5-996b-c18897360d69.png)

![image](https://cloud.githubusercontent.com/assets/17089974/13300030/35ed7354-db0c-11e5-95e4-c8f407638768.png)

**Comment by mikewheaton** [comment]
That seems like a reasonable behavior. I'm not sure when we'll get to this, so you may want to use an override class for now.

**Comment by asith-w** [comment]
is there any update on this ? this really important lot of apps has right cornered icon for navigation

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#36
