### ISSUE TITLE
PeoplePicker: Remove button doesn't work

### ISSUE THREAD

**Issue by manndave** [OfficeDev/office-ui-fabric-core#414]
Button needs to be moved up into parent `li` for JS to work.  PR coming...

Repo steps: click "x" icon in a peoplepicker dropdown to remove result - nothing happens.

**Comment by mikewheaton** [comment]
I'm having trouble attaching event listeners to the `ms-PeoplePicker-resultAction` buttons. Not sure what's going on here.

**Comment by mikewheaton** [comment]
@wdo3650, could you have a look at this one?

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#68
