### ISSUE TITLE
Facepile does not update all user details on embedded PersonaCard

### ISSUE THREAD

**Issue by manndave** [OfficeDev/office-ui-fabric-core#425]
The markup for the Facepile component contains the embedded "template" PersonaCard which is updated dynamically to show the information for the selected user.  The code, though, doesn't update the `ms-Persona-tertiaryText` and `ms-Persona-optionalText` values on the PersonaCard before displaying it.  This means that whatever values are in the "template" PersonaCard for those fields are shown for all users.

**Comment by mikewheaton** [comment]
Thanks for reporting this, David, we'll take a look.

**Comment by manndave** [comment]
I have code to resolve this and the the other Facepile bug I just opened (#426).  It needs a little cleanup and then more testing. I'm swamped this week and beginning of next, but I can whip the code into shape and submit a PR for these if no one else gets to it before I get the chance.

**Comment by mikewheaton** [comment]
We'd really appreciate that, thank you!

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#67
