### ISSUE TITLE
Dropdown: Groupings of dropdown items?

### ISSUE THREAD

**Issue by kennywangjin** [OfficeDev/office-ui-fabric-core#454]
seems that dropdownlist's options could not be grouped. 
I mean:
<select>
 <optgroup label="group a">
  <option>value1</option>
  <option>value2</option>
 </optgroup>
 <optgroup label="group b">
  <option>value3</option>
  <option>value4</option>
 </optgroup>
</select>
Currently, if i add optgroup to select, dropdownlist will flatten these options and groupings are gone!
Is it possible to support grouping in the control? Native <select></select> could just support grouping (although looks pretty plain :)).

**Comment by mikewheaton** [comment]
We'll check in with the designers to see if they've considered option groups. The ContextualMenu component has dividers to separate the menu items into groups, so I'd imagine we would use a similar pattern here.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#66
