### ISSUE TITLE
ContextualMenu: Link text line height is too large

### ISSUE THREAD

**Issue by knutkj** [OfficeDev/office-ui-fabric-core#478]
`ms-ContextualMenu-link` wraps to the next line:

![image](https://cloud.githubusercontent.com/assets/691727/14231771/be321066-f98f-11e5-84ec-1bf4db0991d9.png)

Sample code:

```html
<div class="ms-NavBar">
  <div class="ms-NavBar-openMenu js-openMenu">
    <i class="ms-Icon ms-Icon--menu"></i>
  </div>
  <div class="ms-Overlay"></div>
  <ul class="ms-NavBar-items">    
    <li class="ms-NavBar-item ms-NavBar-item--hasMenu is-selected">
      <a class="ms-NavBar-link">Channels</a>
      <i class="ms-NavBar-chevronDown ms-Icon ms-Icon--chevronDown"></i>
      <ul class="ms-ContextualMenu is-open">
        <li class="ms-ContextualMenu-item">
          <a class="ms-ContextualMenu-link">Many many many animals</a>
        </li>
        <li class="ms-ContextualMenu-item">
          <a class="ms-ContextualMenu-link">Education</a>
        </li>
      </ul>
    </li>
  </ul>
</div>
```

Try it: https://jsfiddle.net/52ohfaL7/

**Comment by mikewheaton** [comment]
Thanks for the detailed report and the JSfiddle. That's everything we need to repro the bug and get it fixed.

**Comment by lixonic** [comment]
@mikewheaton is this a sensible solution ?
![conmenu](https://cloud.githubusercontent.com/assets/934220/15596775/bd6fbe6c-23e7-11e6-9255-88cd43afad4b.png)

**Comment by lixonic** [comment]
![conmenu2](https://cloud.githubusercontent.com/assets/934220/15596994/9c168d34-23e9-11e6-83a9-b79ba16c6e37.png)

**Comment by mikewheaton** [comment]
The second option would be best, as it keeps the entire menu item visible. I'll flag this for a review by our design team to get their thoughts.

**Comment by mikewheaton** [comment]
This issue was reported again in #694. What is the desired behavior here?

**Comment by knutkj** [comment]
I would go for the ellipsis. It could be populated with user input data. You do not know how long the text can be. If to go for text wrap I would limit the number of lines it could be by setting `max-height` to 2 x line height for instance.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#65
