### ISSUE TITLE
Button: Icons inside primary and default buttons?

### ISSUE THREAD

**Issue by alinsirbu** [OfficeDev/office-ui-fabric-core#480]
Hello, I've been working on integrating a uservoice feedback widget into our product and I'm using a couple buttons that have to be the primary button and we want to have an icon inside the button as well. Is that acceptable? If so, I'm asking fabric to make a change that can enable this combination...

At the moment the two classes I'm using are "ms-Button ms-Button--primary" and on top of that I'm using the following styles to enable the icon, line up everything and make the buttons take up the whole width of the panel I render in:

```
.uv-welcome-Button {
    margin: 20px auto;
    
    .ms-Button {
        @include text-align(left);
        width: 100%;
        height: auto;
        min-height: 40px;
        white-space: nowrap;
    }

    .ms-Button-icon {
        display: inline-block;
        vertical-align: middle;
    }

    .ms-Icon {
        @include margin-right(12px);
        font-size: 19px;
        vertical-align: middle;
    }

    .ms-Button-label {
        font-size: 17px;
        font-family: $ms-font-family-semilight;
        display: inline-block;
        width: 85%;
        white-space: normal;
        vertical-align: middle;
    }
}
```

Screenshot:
![image](https://cloud.githubusercontent.com/assets/2481705/14295469/9cbbacac-fb2a-11e5-87b9-026fe081d737.png)

**Comment by mikewheaton** [comment]
It seems reasonable to put an icon inside the default and primary buttons. We'll check in with the designers to see if this is recommended and, if so, remove the `display: none;` that we currently have on `.ms-Button-icon`. For the time being your override styles look fine.

**Comment by mikewheaton** [comment]
It turns out that placing an icon inside a default or primary button is **not** recommended by our design team. They suggest to use a command or hero button instead.
