### ISSUE TITLE
Breadcrumb: Items cannot be modified

### ISSUE THREAD

**Issue by dmitriyyepishin** [OfficeDev/office-ui-fabric-core#485]
If items are added to a Breadcrumb after initial creation, it is not possible to recreate the component to redistribute the items between the main list of items and overflow list.

Also, only one breadcrumb can be created on a page.

Here's a demo of both problems: https://codepen.io/dyepishin/pen/JXMxgz

**Comment by wdo3650** [comment]
@dmitriyyepishin Thanks for pointing out these bugs. We'll take a look.

**Comment by dmitriyyepishin** [comment]
Here's a fix that seems to work: https://codepen.io/dyepishin/pen/WwzbwK/?editors=1010

**Comment by wdo3650** [comment]
@dmitriyyepishin Thanks for offering up a fix. We have a fix in PR currently, #487 . 

The scope of objects running in the prototype needed to be refactored. Also, three new methods have been added which allow the Breadcrumb to be updated on the fly.

- addItem(itemLabel, itemLink, tabIndex) 
- removeItemByLabel(itemLabel)
- removeItemByPosition(position)

You can see the demo of it here: http://codepen.io/anon/pen/qZoWap

**Comment by dmitriyyepishin** [comment]
Nice. Thank you.

**Comment by dmitriyyepishin** [comment]
There are couple issues in the new code:
- If no link is specified when using addItem(), then href is set to “undefined”
- Code comment in removeItemByPosition is incorrect

I also would like to suggest the following additions to the Breadcrumb component, which I used in my app:

- New public method clear, which removes all items from the breadcrumb
- New public method removeItemsAfterPosition, which removes all breadcrumb items after a specified position (this seems to be something often needed)
- Add new style js-auto-remove to breadcrumb div, which, if specified, indicates that when an breadcrumb item is clicked, all items after it should be removed.

Here's a demo: https://codepen.io/dyepishin/pen/LNJXBO

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#63
