### ISSUE TITLE
SearchBox: Fixed width, Search Button, input type

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/office-ui-fabric-core#501]
Currently the search box is implemented to support only a fixed with of 180 pixels. A better solution would be if the search box use the width of the parent container.
This makes it easier to use an provide a better usability.

In addtion a button should be added to execute the search. Currently a manual button needs to be added which might not match the Office UI Language. Especially on mobile devices people rather click a button instead of hitting enter on the keyboard.

Can you please change the input type to 'search'. It provide better support for modern browsers and older browser fall back to use input type 'text' anyway.

**PlaceHolder:** the attribute placeholder can be specified on any input element as well as the search box. Maybe it would be a great addition browser that currently support this attribute can easily provided with a fallback and add the required elements dynamically.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#62
