### ISSUE TITLE
Pivot: ContextualMenu not showing

### ISSUE THREAD

**Issue by jjczopek** [OfficeDev/office-ui-fabric-core#508]
While working on angular version of pivot component, I have recently found out that I can't use contextual menu any more inside pivot ellipsis element.

First pen shows plain pivot component with contextual menu within ellipsis element, based on Fabric 2.2: http://codepen.io/jjczopek/pen/eZLPmL
![image](https://cloud.githubusercontent.com/assets/865473/14832967/14179efe-0bfd-11e6-83a7-0b5c867b9d29.png)

Second pen shows the same setup, with version 2.4 of the Fabric (CSS copied over to codepen as I couldn't find it on CDN): http://codepen.io/jjczopek/pen/zqJmxy
![image](https://cloud.githubusercontent.com/assets/865473/14833003/3f30dec0-0bfd-11e6-8e6a-52736a815dc2.png)

It would be awesome to put content into ellipsis and toggle it's content visibility easily. Is this a bug or expected behavior? If expected, what is the workaround to achieve the same as in Fabric 2.2?

**Comment by mikewheaton** [comment]
Thanks for pointing this out and providing the links that repro the bug. Removing the `overflow-x: hidden;` rule on `.ms-Pivot` seems to do the trick, but I'm honestly not sure why that works or what the rule is needed for in the first place. We'll investigate.

**Comment by jjczopek** [comment]
Any ETA on that? Can we expect this to be fixed with 2.5?

**Comment by mikewheaton** [comment]
We don't have an ETA for this. If you'd like to fix the problem locally you can change the value of `overflow-x` to get it to show. And then when this fix is added to Fabric you could remove the override.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#61
