### ISSUE TITLE
Get latest versions of Fabric on the CDN

### ISSUE THREAD

**Issue by jjczopek** [OfficeDev/office-ui-fabric-core#546]
Official Fabric website has information that styles can be referenced via CDN from http://appsforoffice.microsoft.com.

However the last version that is available there is version 2.2.0, and we are now at 2.5.0. Is that intentional?

Regards,
JC

**Comment by mikewheaton** [comment]
We have submitted the newer versions to the CDN, but unfortunately it can take a long time before they get deployed. I'll leave this issue open so that we can notify you when 2.5.0 is available.

**Comment by mikewheaton** [comment]
All versions of Fabric, up to 2.6.1, are now available on the CDN.
