### ISSUE TITLE
Button: Request for a smaller variant

### ISSUE THREAD

**Issue by jbarr33** [OfficeDev/office-ui-fabric-core#605]
Consider that the "base" button should not have any size attributes at all.  If you want a specific type of button like small, medium, or large an inherited class can be created with the appropriate sizes.  Ex. "ms-Button ms-Button-sm".

The button right now is not always suitable sizing for a task pane add-in.
  height: 32px;
  min-width: 80px;
  padding: 4px 20px 6px;

**Comment by ericthompson** [comment]
Could you send us a screenshot of how this button appears in your add-ins? This would help us understand what you're shooting for and how our current pattern doesn't fit.

**Comment by jbarr33** [comment]
Thanks for the reply.  I can't send a screenshot right now.  Basically, I just want a smaller button which I can accomplish by using ms-Button and then overriding the height, min-width, and padding in a new CSS class.  It's just that a button with a min-width of 80 (padding left/right of 20px each) takes up 1/4 of the width of a default task pane (1/3 if on a smaller device like a surface) which can make layout difficult sometimes.

**Comment by mikewheaton** [comment]
I've reached out to one of our designers who works specifically in the add-in space to get an answer for you.

**Comment by v-chloc** [comment]
Hey Mike, has this issue been resolved? I was going to take a look into it, but wanted to check with you before I proceed. 

Thnx

**Comment by mikewheaton** [comment]
@v-chloc: The design team is discussing whether or not to include a smaller button variant. So I don't think there's anything to be done here yet.

**Comment by v-chloc** [comment]
@mikewheaton Do you know which design team? I should have mentioned that I'm working on Jeffrey Dunn's design team. He had asked to reach out. Feel free to let me know if this is getting sorted out elsewhere though.

**Comment by mikewheaton** [comment]
@v-chloc: I'll send you an email. :)

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#59
