### ISSUE TITLE
CommandBar: Disabled split buttons still work

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#612]
When `ms-CommandButton` has the `is-disabled` state it appears disabled. However, if that button contains a dropdown it still works as usual. It should be disabled.

![image](https://cloud.githubusercontent.com/assets/1382445/15628670/c49b8ce6-24bb-11e6-9ab8-df22de895242.png)

![image](https://cloud.githubusercontent.com/assets/1382445/15628679/00c48d44-24bc-11e6-9f91-79fa06204eb6.png)

**Comment by lixonic** [comment]
@mikewheaton how to recreate the same

**Comment by mikewheaton** [comment]
@lixonic: To see this new style of button (along with many other changes) you can pull down the `beta/3.0.0` branch. I actually shouldn't have opened this issue on GitHub yet, as the issues reflect what needs done on our main branch. The changes for Fabric 3.0.0 will be merged into `master` in the next few days. 😄

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#58
