### ISSUE TITLE
DatePicker: Don't scroll the page when it opens

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#641]
Right now whenever the DatePicker is opened we scroll the page so that the input is at the top. This is very annoying (scrolling is up to the user, not us) and still doesn't guarantee that there's room for the picker to open below the input. Let's instead open it up wherever there is available room.

**Comment by Fensterbank** [comment]
Full agreement from my point of view.
In my case we used the DatePicker inside a SharePoint 2013 `SP.UI.ModalDialog` and this full page scroll effect was so wrong.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#48
