### ISSUE TITLE
Pivot: clicking below the label does not cause any action

### ISSUE THREAD

**Issue by marekszala-microsoft** [OfficeDev/office-ui-fabric-core#647]
When I click the space between a label and its bottom bar a selection animation is played but the selected item does not change.
See the attachment:
![pivotclickbug](https://cloud.githubusercontent.com/assets/19771931/15814406/ef56e9fa-2bc6-11e6-9ed8-ad8d9107ec9e.gif)

**Comment by mikewheaton** [comment]
Thank you for reporting this bug, @marekszala-microsoft

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#42
