### ISSUE TITLE
Table: Inconsistency with new SharePoint table design

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/office-ui-fabric-core#657]
Just wanted to let you know that the Office UI Fabric table design is inconsitent with the new SharePoint and Office 365 Design. 

Office UI Fabric use squared boxes.
<img width="807" alt="screen shot 2016-06-09 at 23 59 47" src="https://cloud.githubusercontent.com/assets/5503835/15948074/1b5d0f7c-2e9f-11e6-86e2-70f7cc3d85d3.png">

All other Office 365 Applications use round check boxes.

<img width="671" alt="screen shot 2016-06-09 at 23 54 54" src="https://cloud.githubusercontent.com/assets/5503835/15948199/aeeb4ce0-2e9f-11e6-9323-1ec5e4857ec8.png">

**Comment by mikewheaton** [comment]
Thanks for bringing this up, I've flagged it for our design team to review.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#41
