### ISSUE TITLE
Documentation: DatePicker JS has a bug

### ISSUE THREAD

**Issue by Fensterbank** [OfficeDev/office-ui-fabric-core#661]
I implemented DatePicker with your sample code in my application and got an infinite loop when using the month picker to change the selected month.

The problem occured in your example function `changeHighlightedDate` where the `undefined` checks don't work.

![loop](https://cloud.githubusercontent.com/assets/1684826/16006567/092b06f2-316e-11e6-8684-7e75b37d53c9.png)

The picker highlight function was called with two undefined values in the array which resulted in an infinite loop.

Why did you use such unusual `undefined` checks?
when `foo` is `undefined`, `typeof(foo)` would return a string `'undefined'`.
I don't think the `typeof` function would ever return an empty string.

I would have just used `if (newYear == undefined)` or `if (typeof(newYear) == 'undefined')`.
Also `if (isNaN(newYear))` could be a nice solution to prevent bad parameters for the picker's highlight function.

**Comment by mikewheaton** [comment]
Have you tried your changes to confirm that it fixes the issue? If so, we'd love a pull request so that we can incorporate this fix.

**Comment by Fensterbank** [comment]
Okay, I just wanted to provide a small pull request when I realized, the issue is not in the code.
This explains why the bug doesn't occure on your sample site.

[Here](https://github.com/OfficeDev/office-ui-fabric/blob/master/src/components/DatePicker/Jquery.DatePicker.ts#L225) we see the following code:
```
if (typeof newYear === "undefined" || newYear === null) {
    newYear = $picker.get("highlight").year;
}
```
This is okay and works, but your DatePicker JS example on http://dev.office.com/fabric/components/datepicker does have another code, which would not work how it should.
I didn't find the sample code in your Repository, so it seems to be a documentation bug on your sample site only.

**Comment by mikewheaton** [comment]
Thanks for tracking the bug down. When we update our documentation site for 3.0 it will pull in the sample directly from Fabric, so this issue should be resolved then. I'll keep this bug opened to be sure that we get it fixed.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#40
