### ISSUE TITLE
CommandBar:Layout problem

### ISSUE THREAD

**Issue by Brian-Ding** [OfficeDev/office-ui-fabric-core#668]
i am playing with newly released 3.0.0 beta, it is great that navbar and commandbar are merged into a single component.

i found some html code like this in ./documentation/Components/CommandBar/index.html
>              
                
                <div class="ms-CommandButton ms-CommandBar-overflowButton ms-CommandButton--noLabel">
                    <button class="ms-CommandButton-button">
                        <span class="ms-CommandButton-icon "><i class="ms-Icon ms-Icon--ellipsis"></i></span><span class="ms-CommandButton-label"></span>
                    </button>
                    <ul class="ms-ContextualMenu  is-opened ms-ContextualMenu--hasIcons">
                        <li class="ms-ContextualMenu-item ">
                            <a class="ms-ContextualMenu-link " tabindex="1">Folder</a>
                            <i class="ms-Icon ms-Icon--folder "></i>
                        </li>
                        <li class="ms-ContextualMenu-item ms-ContextualMenu-item--divider"></li>
                        <li class="ms-ContextualMenu-item ">
                            <a class="ms-ContextualMenu-link " tabindex="1">Plain Text Document</a>
                            <i class="ms-Icon ms-Icon--document "></i>
                        </li>
                        <li class="ms-ContextualMenu-item ">
                            <a class="ms-ContextualMenu-link " tabindex="1">A Dog</a>
                            <i class="ms-Icon ms-Icon--dogAlt "></i>
                        </li>
                        <li class="ms-ContextualMenu-item ">
                            <a class="ms-ContextualMenu-link " tabindex="1">The Sun</a>
                            <i class="ms-Icon ms-Icon--sun "></i>
                        </li>
                        <li class="ms-ContextualMenu-item ">
                            <a class="ms-ContextualMenu-link " tabindex="1">Money</a>
                            <i class="ms-Icon ms-Icon--money "></i>
                        </li>
                    </ul>
                </div>
                

1. the weired thing is, if i delete any of those li inside ul label, seems has no effect. Everything is still the way it was. Could anyone help me the logic here?
2. if i comment out the whole ul section, "..." will always be showing in the commandbar, no matter what size of my browser is
3. if l leave the code the way it is, in a large screen, everything works fine. but when i adjust browser(Edge) to be a smaller size, click on "..." does popup the list of buttons, but clicking on these buttons has no effect, no navigation, nothing happens

i referen these js files
>    fabric.js
      fabric.templates.js
      PickaDate.js

and add the js code like below

>      var CommandBarElements = document.querySelectorAll(".ms-CommandBar");
        for (var i = 0; i < CommandBarElements.length; i++) {
            new fabric['CommandBar'](CommandBarElements[i]);
        }

Any help is appreciated, thank you!

**Comment by Brian-Ding** [comment]
anyone?

**Comment by mikewheaton** [comment]
@battletoilet: Could you take a look at this one, as you'e worked the most on the new CommandBar?

**Comment by battletoilet** [comment]
Hey @Brian-Ding apologies for the delayed response.

1. Currently there is now way to just re-render the contextual menu inside the CommandBar manually. You will probably  have to Re-render the command bar for now until we can more helpful public methods on CommandBar.
2. If you don't want the contextual menu the command bar will only understand that if you remove the entire ContextualMenu component not just the li's.
3. Right now ContextualMenu  doesn't have have a callback for each item, we should have a method like this in a future release. For now you will need to attach your own events to ContextualMenu items in the CommandBar.

I hope that helps! Let me know if you have anymore questions.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#38
