### ISSUE TITLE
NPM warnings

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#674]
When running `npm install` on a fresh clone of the Fabric repo, there are warnings of deprecated NPM packages:

![image](https://cloud.githubusercontent.com/assets/1382445/16203356/b483f454-36ce-11e6-9b4b-52e51e33174a.png)

**Comment by leddie24** [comment]
![screen shot 2016-09-23 at 3 20 07 pm](https://cloud.githubusercontent.com/assets/1291968/18802977/3f818162-81a1-11e6-86c2-2a80d6987b02.png)

Here's the list of my npm install deprecated files as of today (with a clean clone).  None of these (lodash, minimatch, graceful-fs) are in our actual dev dependencies, so it's out of the scope of the issue to fix them.  Closing for now, we can investigate in the future if this list changes.
