### ISSUE TITLE
MessageBanner: Document/implement showing and hiding

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-ui-fabric-core#680]
The JS version of MessageBanner exposes a hideBanner() method. This is not exposed in the TypeScript verson. As a result the only way that the MessageBanner can be hidden on startup, which is normally what a developer would want, is to add the class "is-hidden" to the <div> with ms-MessageBanner class. But the MessageBanner.hbs file that is included does NOT do this. Also, there could be scenarios, other than startup, when calling code will need to hide a MessageBanner. I *think* you just have to change 
private _hideBanner():
to
public hideBanner():

**Comment by mikewheaton** [comment]
Thanks for reporting this, @Rick-Kirkham. Showing and hiding a MessageBanner is essential functionality. We'll take a look at the JS and make sure that our documentation clearly shows how to accomplish this.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#28
