### ISSUE TITLE
Panel: Page can scroll while PanelHost is open

### ISSUE THREAD

**Issue by battletoilet** [OfficeDev/office-ui-fabric-core#683]
If the page goes beyond the screen size and Panel is opened, PanelHost does not stop the screen from scrolling and causes the panel to stay at the top of the screen. See screenshot below.
![image](https://cloud.githubusercontent.com/assets/622498/16279390/9fd19d5c-386f-11e6-8154-43e851e88595.png)

**Comment by lixonic** [comment]
similar behaviour in overlay too.  
![image](https://cloud.githubusercontent.com/assets/934220/16368474/4bc460ec-3c4c-11e6-82ad-f13da52e957d.png)

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#27
