### ISSUE TITLE
Checkbox not filled in Office Add-in

### ISSUE THREAD

**Issue by bclevering** [OfficeDev/office-ui-fabric-core#684]
![issuenocheckincheckbox](https://cloud.githubusercontent.com/assets/8439274/16298677/f8ef9836-3936-11e6-90fe-a4badb9fccd8.png)

When i start my add-in into word the checkbox is not loaded within the checkbox; 
When i start it with IE (or Chrome) the checkbox is correctly filled.

![inieitsworking](https://cloud.githubusercontent.com/assets/8439274/16298792/64c35386-3937-11e6-92d9-8747d59ff4d8.PNG)

**Comment by bclevering** [comment]
i've found the problem: The fonts are loaded from https://appsforoffice.microsoft.com; but this domain cannot be used within the add-in?

**Comment by mikewheaton** [comment]
The fonts should be loading within your add-in; this is one of the most common use cases for Fabric. I'm not familiar with add-in debugging. Is there a way to see the network requests?

**Comment by bclevering** [comment]
The fonts are loading (if i look within fiddler) and also returning a HTTP 200 but then it looks if though it's not loading (or blocked being loaded) It could be a Office Policy or so which blocks this usages of external fonts or so?

When i look on my development machine the fonts are loaded correctly.

**Comment by mikewheaton** [comment]
Very strange. I'll see if I can find someone more familiar with add-ins who can help you with this issue.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#71
