### ISSUE TITLE
Dropdown: Hides behind content-header in office Add-In

### ISSUE THREAD

**Issue by jonasrk** [OfficeDev/office-ui-fabric-core#686]
My ms-Dropdown hides behind the content-header in my office Add-In:

![screen shot 2016-06-23 at 6 12 26 pm](https://cloud.githubusercontent.com/assets/2970342/16310965/e1ff5822-396e-11e6-8726-1fda97819f9e.png)

    <body class="ms-font-m">
    <div id="content-header">
        <div class="padding">
            <h1>Merge columns</h1>
        </div>
    </div>
    <div id="content-main">

     <div id="step1">
        <div class="padding">
            <div class="ms-Dropdown dropdown_table" tabindex="1">
                <label class="ms-Label">Select table1</label>
                <i class="ms-Dropdown-caretDown ms-Icon ms-Icon--caretDown"></i>
                <select id="table1_options" class="ms-Dropdown-select"></select>
            </div>`

Changing position in

`.ms-Dropdown.is-open .ms-Dropdown-items {
  display: block;
  position: fixed;
}`

to relative makes it better, but that way it's not looking fabric-y anymore.

**Comment by mikewheaton** [comment]
You'll want to check the `z-index` of the header div and compare it to that of `ms-Dropdown-items.` Then you can either increase the `z-index` of the dropdown or decrease the header until the stacking order is what you want.

**Comment by jonasrk** [comment]
When I expect my elements in Chrome I see that the z-index of the drowdown is `2` and the content-header is `auto`.

I had not mentioned that it works perfectly fine in Excel Online on Chrome. It's just not working in Excel 2016 itself.

I have tried manipulating the z-indices in my .css - didn't help.

I'm using Vorlonjs to connect to the Add-In running in Excel 2016 to use Javascript to change the z-index at runtime - also didn't help.

**Comment by mikewheaton** [comment]
I'll see if I can find someone more familiar with add-ins who can help you with this issue.

**Comment by sumurthy** [comment]
@jonasrk - what happens when you try this in Internet Explorer browser on the same machine where you have the desktop/Excel 2016 related issue?

**Comment by jonasrk** [comment]
Hmm, I can't test on Internet Explorer since I'm using a macOS machine. In chrome it looks like this:

![screen shot 2016-06-25 at 4 29 44 pm](https://cloud.githubusercontent.com/assets/2970342/16357271/1942445a-3af2-11e6-8b88-42d40485a6f1.png)

**Comment by sumurthy** [comment]
@jonasrk - sorry I'm still not clear. Can you confirm the platform you are facing this issue in (for the first screen shot)? (MAC + office rich-client ) or (Mac + Safari + Online) or (Mac + Chrome + Online)?

**Comment by jonasrk** [comment]
Unfortunately, the issue is not easy to reproduce:

- It happens on one machine (Mac + Chrome + Online) and not on another with that configuration.

- (Mac + Safari + Online) seems to always have the issue.

- It does happen in (Windows + Office Offline). Here only the white background of the dropdown is hidden, but the textlabels still shine through:

![capture](https://cloud.githubusercontent.com/assets/2970342/16895432/3e3ff2fe-4b76-11e6-90df-da8c32fcaa29.PNG)

- On (Windows + Windows Edge 20.10 + Online) it works fine.

- On (Windows + IE11 + Online) it works fine.

I did notice one rather odd thing: When I import vorlon for debugging Windows Offline Excel, the issue disappears. When I comment it out, it comes back again.

**Comment by jonasrk** [comment]
Also setting `overflow: visible;` for `#content-main` seemed to have helped.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#70
