### ISSUE TITLE
Documentation: Font weight table headings in wrong order

### ISSUE THREAD

**Issue by DwayneSmurdon** [OfficeDev/office-ui-fabric-core#688]
On http://dev.office.com/fabric/styles there is a **Font weight** section.  Under it are two columns and the "class" and "weight" columns are swapped.

Also, I believe it would prove useful for this information (styles) could be included under  the dist/documentation folder.

**Comment by mikewheaton** [comment]
Thanks for reporting this, @DwayneSmurdon. We'll get it fixed for our next website release.

Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/1382445/16347322/f0657742-3a00-11e6-826b-6610032e765a.png)

**Comment by DwayneSmurdon** [comment]
Hello!

In an effort to spend more time reading your emails and less time organizing spam, I've changed my email address.  It is now: =dsmurdon at predictable data dot com=; without spaces, equal signs or the word 'at', of course.  Please resend your email there.

I apologize for the inconvenience and appreciate your help.  I look forward to reading your email.

Sincerely,

-Dwayne

**Comment by DwayneSmurdon** [comment]
Glad to see it will be fixed!  Any thoughts about including the content from this page in the dist/documentation folder?

**Comment by mikewheaton** [comment]
We have no timeline for this work but yes, we do want to get all of the documentation content (such as font styles, colors, animations, etc.) into the main Fabric repo. This will make it easier to contribute to the project's documentation and prevent bugs where we sometimes change Fabric and forget to update the docs.

**Comment by DwayneSmurdon** [comment]
Indeed.  I look forward to the next release.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#29

**Comment by mikewheaton** [comment]
Accidentally copied over to Fabric JS. This is a Fabric Core issue. Reopening.

**Comment by mikewheaton** [comment]
This issue has been moved into an internal system where we track work items for the documentation site.
