### ISSUE TITLE
CommandBar: Event handlers lost when moved into overflow

### ISSUE THREAD

**Issue by MJZawacki** [OfficeDev/office-ui-fabric-core#691]
I'm seeing issues in an Office add-in on Mac where the event is not fired when the command is hidden in the overflow menu.

What is the intended way to link up click events so that they work while inside the overflow menu? The element id's from the original ms-CommandBarItem's are not persisted by createMenuItem so it's unclear to me how you intended to hook up the event.

**Comment by mikewheaton** [comment]
This bug repros in Fabric 3.0 as well. If you set an onClick handler on a CommandButton, that handler is lost when the button is moved into the overflow menu.

**Comment by schott12521** [comment]
I was able to add a link for the overflow buttons using this snippet in the javascript function for createMenuItem:

```javascript
var item = '<li class="ms-ContextualMenu-item"><a class="ms-ContextualMenu-link" href="' + linkToButton + '">';
item += /* Button link action */
item += '</a></li>';
```

However, I'm running into some more problems with the commandBar and it's overflow now. If I click outside the area that turns the mouse into a pointer, I will be correctly taken to the link using my method above. However, if I click inside the actual ellipsis area that turns my mouse into a pointer, the overflow will pop open, but no action will be taken.

Additionally, if I click outside the pointer area, I can click multiple command bar overflows and it will not cause the other overflows to hide.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#26
