### ISSUE TITLE
PeoplePicker: Filter results while typing

### ISSUE THREAD

**Issue by johnnyongesa** [OfficeDev/office-ui-fabric-core#701]
Hi Guys, I have managed to read all users from sharepoint and added ui fabric people picker, but its show all the user in the list. I want it behave same way as the old people picker. List user as the user types

**Comment by ericthompson** [comment]
Hi, @johnnyongesa!  When you refer to the "old" people picker, are you referring to a Fabric one or [this people picker](https://github.com/OfficeDev/Office-365-People-Controls) (or maybe something different)?

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#24
