### ISSUE TITLE
Where to get the HTML for components?

### ISSUE THREAD

**Issue by manndave** [OfficeDev/office-ui-fabric-core#712]
Is the gulp build process supposed to generate HTML files?  All I'm getting in the dist\components\* folders are .hbs, .json, and .scss.  What am I doing wrong?

Thanks.

**Comment by manndave** [comment]
Update/clarification:

I get all of the index.html files under _dist\documentation\components\_*  but the only .html files I get under _dist\components\_* are **Dropdown.Disabled.html**, **Toggle.Disabled.html**, **Toggle.TextLeft.html** and of those, only **Toggle.Disabled** has HTML in it, the other 2 have the HandleBars markup.

I'm not completely sure what the goal is, so I'm not sure what to expect.  

Thanks,

Dave

**Comment by mikewheaton** [comment]
Thanks for reporting this @manndave, I can see how it would be confusing to have just those files. Those were leftovers and I've opened PR #715 to remove them.

In the `dist/components/*` folders you'll find a JSON file describing the component, its SCSS styles, and a Handlebars template that is used to generate the HTML. This closely matches the `src/components/*` folders, with the difference being that they also include TypeScript files where necessary. In `src/documentation/pages/*` we have a folder for each component, with JS files to specify the props that are passed to the Handlebars components at build time.

Over in `dist/documentation/Components/*` you'll find a single HTML page that documents that component. This is what you see when you `gulp watch` and go to http://localhost:2020 and the body content of these pages is pulled directly into the Fabric website.

I'll close this issue for now, but please let us know if you have any other questions or see something that doesn't look quite right.

**Comment by manndave** [comment]
@mikewheaton:  Thanks for that.  I had worked all of that out, but I guess the question is what should a person who just wants to use Fabric (so doesn't care about the build process, typescript, handlebars, etc) look for?  In the blog post about 3.0 it says that the build process creates HTML files - is this the files in `dist/documentation/components/*` which have a lot more than just the HTML?  Are users expected to copy the HTML they need from there?  I ask because, while I'm OK with that, I'm not sure that's best for devs under a deadline.  I'm also looking at the automated generation of snippets and an updated Pluralsight course for Fabric v3 and want to know the best thing to teach people.

Thanks,

Dave

**Comment by mikewheaton** [comment]
We're thinking that code samples would be copy-pasted from the documentation site. However, I don't know that we'll have those code snippets includes in time for the 3.0 release this week. With the current build it's very hard to get the HTML for a given component – you'd have to actually view the HTML source within `dist/components/*`.

I'll reopen this issue so that we can discuss our best quick fix for this. @battletoilet, thoughts?

**Comment by manndave** [comment]
OK, makes sense.   I'm working on some additions to the build process to get the snippets automatically created from the hbs files (I sent you an email with some questions).  Definitely won't have anything in place for a release this week, though.  I'm just beginning the Pluralsight course, so maybe there's time to get it worked out before it's finished.  I'm game to contribute whatever I can to help.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#20
