### ISSUE TITLE
Callout [2.6.1]: Invalid CSS calc

### ISSUE THREAD

**Issue by Etheryte** [OfficeDev/office-ui-fabric-core#722]
The latest stable release, 2.6.1, has a bug in the Callout component.  
[Line 280 in Callout.scss](https://github.com/OfficeDev/office-ui-fabric/blob/release/2.6.1/src/components/Callout/Callout.scss#L280):

    top: calc('50% - 10px');

Both the line above and the generated CSS (which is identical), are naturally [invalid CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/calc).  
The fix would be to remove the unnecessary apostrophe:

    top: calc(50% - 10px);

The component isn't unusably broken as a different (static) value is inherited from elsewhere, but it never functions as intended.

**Comment by ericthompson** [comment]
Thanks for noting this, @Etheryte. Filed!

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#19
