### ISSUE TITLE
Add version number as comment to JS files

### ISSUE THREAD

**Issue by manndave** [OfficeDev/office-ui-fabric-core#725]
The css files have a comment at the top `/**  * Office UI Fabric 3.0.0  *`.  Please consider adding this to the JS (and conceivably the hbs, scss and json ) files so that automated tooling can check version numbers.  It could be done via a Gulp task to streamline it.

Thanks.

**Comment by manndave** [comment]
*Bump*

**Comment by ericthompson** [comment]
Good point - filed!

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#17
