### ISSUE TITLE
Path to Libraries incorrect in samples HTML

### ISSUE THREAD

**Issue by dmitriyyepishin** [OfficeDev/office-ui-fabric-core#727]
Sample HTML files in documentation\Components\ has incorrect have incorrect path to Fabric JS and CSS files. The path is missing one "..". For example

`<script type="text/javascript" src="../../js/fabric.js"></script> `

should be

`<script type="text/javascript" src="../../../js/fabric.js"></script>`

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#16
