### ISSUE TITLE
Inconsistency in CSS for multiline and single line textboxes

### ISSUE THREAD

**Issue by schott12521** [OfficeDev/office-ui-fabric-core#730]
A multiline textbox has a fontfamily of Segoe UI Regular, whereas a normal textbox has a fontfamily of Segoe UI Semilight. This is a small issue, and it is definitely just me being nitpicky, but due to the priority / specificity of the CSS, I think making note of the inconsistency is a good thing!

**Comment by mikewheaton** [comment]
Which version of Fabric are you seeing this in? It should have been fixed by PR #607.

**Comment by schott12521** [comment]
Currently using Office UI Fabric 2.6., so thanks for the update.

**Comment by mikewheaton** [comment]
Okay, looks like this issue has been fixed and will be included in the [Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js) 1.0 release.
