### ISSUE TITLE
Office theme in Fabric best practice

### ISSUE THREAD

**Issue by cut2run** [OfficeDev/office-ui-fabric-core#732]
Hello,

Would you mind to clarify on best practice to use "Office.context.officeTheme" object to set appropriate theme in the Fabric. 

There are 3 Office themes:
1. Colorful
2. Dark Gray
3. White

There are 4 object properties:
1. bodyBackgroundColor (colorful: e6e6e6; dark: 6a6a6a; white: ffffff)
2. bodyForegroundColor (colorful: 444444; dark: f0f0f0; white: 444444)
3. controlBackgroundColor (colorful: fdfdfd; dark: d4d4d4; white: fdfdfd)
4. controlForegroundColor (colorful: 444444; dark: 262626; white: 444444)

Is there any corresponding CSS classes in Fabric I can use to set those colors/themes? Can I set the theme per page once or I need to set each color for every single control I use on the page? Basically I'd like to know I you have some "Colorful" class corresponding to Office properties or I have to set those colors manually, when retrieved?

This particular way I don't like as I have to take care about every element I use:

`function applyOfficeTheme(){
    // Get office theme colors.
    var bodyBackgroundColor = Office.context.officeTheme.bodyBackgroundColor;
    var bodyForegroundColor = Office.context.officeTheme.bodyForegroundColor;
    var controlBackgroundColor = Office.context.officeTheme.controlBackgroundColor
    var controlForegroundColor = Office.context.officeTheme.controlForegroundColor;

    // Apply body background color to a CSS class.
    $('.body').css('background-color', bodyBackgroundColor);
}`

Please let me know.
Thank you.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#14
