### ISSUE TITLE
Office UI Fabric code snippets

### ISSUE THREAD

**Issue by sivarajanr** [OfficeDev/office-ui-fabric-core#740]
Team,

I have created the Office UI Fabric code snippets for Visual Studio Code. 

https://marketplace.visualstudio.com/items?itemName=sivarajanraju.vs-code-office-ui-fabric

Please include in Office UI Fabric resources section.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#12
