### ISSUE TITLE
Dialog: Font-size 0 

### ISSUE THREAD

**Issue by jigargandhi** [OfficeDev/office-ui-fabric-core#744]
The `ms-Dialog` class has set `font-size:0` explicitly. 
This causes elements without OfficeUI's classes to have a size of 0 pixels and hence invisible. 
See [plnk](http://plnkr.co/edit/bTKE1YMjEkyX1NdM5DrM?p=preview) for sample.

Expected Output:
`ms-Dialog` should not have `font-size` set.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#11
