### ISSUE TITLE
@keyframes animation doesn't contain prefixed version

### ISSUE THREAD

**Issue by s-KaiNet** [OfficeDev/office-ui-fabric-core#745]
All CSS3 key frame animation doesn't contain prefix version for Chrome, i.e.
`@-webkit-keyframes fadeIn`. Chrome still requires prefix according to [this](http://shouldiprefix.com/#animations).  
You have ready to use animation such as `.ms-u-fadeIn400` which is prefixed, but sometimes it's useful to create your own using key frame animation name.   
For example angular 1.x adds its own classes for animation `[class-name]-add, [class-name]-remove`, etc. so it's not possible to use classes such as `.ms-u-fadeIn400`. But it's possible to provide your own animation rule using key frame from fabric.css: 
```
.is-open-add{
    animation: 0.367s cubic-bezier(0.1, 0.9, 0.2, 1) fadeIn, slideRightIn40;
    -webkit-animation: 0.367s cubic-bezier(0.1, 0.9, 0.2, 1) fadeIn, slideRightIn40;
    -webkit-animation-fill-mode: both;
    animation-fill-mode: both;
}
```  
But currently this is broken in Chrome because of missing prefix for `@keyframe`.   
Sorry, accidentally mentioned user with name `@keyframe` :)

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#10
