### ISSUE TITLE
Question: Best practice for a ContextualMenu used for filtering and sorting?

### ISSUE THREAD

**Issue by schott12521** [OfficeDev/office-ui-fabric-core#746]
I'm trying to make a ContextualMenu for filtering and sorting lists and tables and such, and I'm wondering what the best way to achieve something like the menu used in Office 365's Outlook app, seen here: ![contextualmenu](https://cloud.githubusercontent.com/assets/1456022/17180874/70473c86-540d-11e6-9488-9ef48fccb759.png)

It seems that all the ContextualMenu javascript doesn't do that much, and if I have the ContextualMenu inside a CommandBar or NavBar, then I can't have submenus and the is-selected doesn't persist, it only can take me to an href. Any suggestions would be awesome, thanks.

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#9
