### ISSUE TITLE
[Breadcrumb]: Missing first chevron icon

### ISSUE THREAD

**Issue by atneik** [OfficeDev/office-ui-fabric-core#751]
Missing first chevron icon. The one between ellipsis and Folder 4. Or is it by Design?
<img width="473" alt="screen shot 2016-07-28 at 2 33 06 pm" src="https://cloud.githubusercontent.com/assets/785361/17230323/59b4333e-54d0-11e6-942a-98debf8f2f72.png">

**Comment by mikewheaton** [comment]
Great catch, there should be a chevron there like so:

![image](https://cloud.githubusercontent.com/assets/1382445/17230942/ff0061b6-54d3-11e6-8c3d-a5aaaa9086db.png)

**Comment by mikewheaton** [comment]
This issue was moved to OfficeDev/office-ui-fabric-js#8
