### ISSUE TITLE
Icons are not properly aligned in Mac OS outlook desktop 2016

### ISSUE THREAD

**Issue by asith-w** [OfficeDev/office-ui-fabric-core#768]
Icons are not properly aligned in Mac OS outlook desktop 2016.
![screen shot 2016-08-11 at 1 37 01 pm](https://cloud.githubusercontent.com/assets/5784846/17582359/dcf0dc90-5fc8-11e6-8eea-e45a73d0049a.png)

**Comment by mikewheaton** [comment]
This looks fine on both Chrome and Safari on Mac, so it does seem to be related to the add-in frame in Outlook. Could you open this issue in the [Fabric JS project](https://github.com/OfficeDev/office-ui-fabric-js/issues), where the Command Bar is now located?
