### ISSUE TITLE
new icons - application specific icons

### ISSUE THREAD

**Issue by johnnliu** [OfficeDev/office-ui-fabric-core#780]
Hi, it's me again.  The guy from #113 

I noticed with the new SPFx, there are new icons available for applications.  That's great!

https://blog.mastykarz.nl/specify-icon-sharepoint-framework-client-side-web-part/

OfficeUIFabric core doesn't seem to have been updated yet though.

Also, how does icons like W (word) work when you flip it right to left? #779

**Comment by mikewheaton** [comment]
Fabric Core has been updated with these new icons, but our website is currently out-of-date and showing the old icon set. To view a list of the icons in our latest version see [this SCSS file](https://github.com/OfficeDev/office-ui-fabric-core/blob/master/src/sass/Fabric.Icons.Output.scss).

As for right-to-left support, only icons that are 'directional' will be flipped. So an arrow that originally pointed to the right would now point left, but the letter W would remain the same. You can see [this example](http://plnkr.co/edit/T8otSgCuOCuF8zTrbPuN?p=preview) where we flip the arrows, while leaving the tag icon the same.

![image](https://cloud.githubusercontent.com/assets/1382445/17815706/662c20d8-65ea-11e6-8ade-0df55d66d0a6.png)
