### ISSUE TITLE
how to pick up the SharePoint theme

### ISSUE THREAD

**Issue by simibac** [OfficeDev/office-ui-fabric-core#783]
Hello everybody,
I'm currently working on a visual web part for SharePoint 2013. This web part should adjust its colors to the SharePoint theme. So far I can use Fabric UI for styling but it does not adjust dynamically. E.g. when I choose a dark SP (e.g. lime) theme the text is hardly readable.
![sp](https://cloud.githubusercontent.com/assets/15369592/17897008/de129080-6952-11e6-9ea7-74b1e9ac4a1d.png)

In the documentation of Office UI Fabric is says: "When the theming system is enabled and your app or add-in is consuming the suite navigation, these classes pick up the user's chosen theme."

Can someone please tell me how this can be done? How do I enable the theming system and how can my web part consume the suite navigation?

If I understood the documentation correctly it can be used similarly to the styling of chrome control (https://msdn.microsoft.com/en-us/library/office/jj220046.aspx).

**Comment by ericthompson** [comment]
Hi @simibac,

Thanks for the request. Unfortunately, the [document you linked to is correct](https://msdn.microsoft.com/en-us/library/office/jj220046.aspx) in that Fabric, at the moment, doesn't support SharePoint themes. I'm curious where you read that documentation about theming working with the suite navigation for Fabric. It would be good to see the context.

**Comment by ericthompson** [comment]
Going to close for now as the documentation states that Fabric doesn't currently support SharePoint themes:
![image](https://cloud.githubusercontent.com/assets/1420854/18209492/c8402e28-70e8-11e6-9fda-e7fc48f9d3e6.png)

We certainly hope to support them in the future, but currently do not have a timeframe. Please let us know if you find the documentation that explains otherwise so we can update it. Thanks!

**Comment by KTITS-Tom** [comment]
But line 4 of [color documentation](https://github.com/OfficeDev/office-ui-fabric-core/blob/master/src/documentation/pages/Color/index.html) says theming is supported. You should upate your docs.

**Comment by ericthompson** [comment]
Thanks for pointing this out, @KTITS-Tom - I've got #800 to rectify this.

We're looking into hooking into theming more broadly, and can provide updates when this is set up.
