### ISSUE TITLE
Icons not loading in Safari

### ISSUE THREAD

**Issue by Chethansannju** [OfficeDev/office-ui-fabric-core#787]
Hi,

I'm using office fabric ui in our project and i found a issue that the office fabric icons are not getting loaded in safari browser where as it works well in all other browsers. Please let me know what i need to do..

**Comment by ericthompson** [comment]
Looking into this now to see if we can repro.

**Comment by ericthompson** [comment]
We tested this out and didn't have it repro. Are you still seeing this issue?

**Comment by ericthompson** [comment]
Please let us know if there are more details and I can reopen.

**Comment by patrickabel** [comment]
@ericthompson I am seeing this issue as well.

**Comment by ericthompson** [comment]
@patrickabel and @Chethansannju - What versions of Fabric are you both using? Just trying to narrow down between the latest and the older set.

Thanks for any info!

**Comment by leddie24** [comment]
Hi @patrickabel.  I just tried reproing this with a page with some random icons and couldn't see the issue.  Running OS X v 10.12, Safari Version 10.0 (12602.1.50.0.10), Fabric core version 4.0.0 from the CDN.  Can you update the ticket with a code snippet and other information?

Thanks

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Test</title>
	<link rel="stylesheet" href="https://appsforoffice.microsoft.com/fabric/fabric-core/4.0.0/fabric.min.css">
</head>
<body>
	<ul>
		<li><i class="ms-Icon ms-Icon--Mail" aria-hidden="true"></i></li>
		<li><i class="ms-Icon ms-Icon--MapPin" aria-hidden="true"></i></li>
		<li><i class="ms-Icon ms-Icon--Pin" aria-hidden="true"></i></li>
		<li><i class="ms-Icon ms-Icon--FavoriteStar" aria-hidden="true"></i></li>
	</ul>
</body>
</html>
```

**Comment by ericthompson** [comment]
@Chethansannju and @patrickabel - could you let us know what versions of macOS, Safari, and Fabric you're using?

**Comment by ericthompson** [comment]
We're going to go on ahead and close this, but let us know if you have more info - we're not able to repro.

**Comment by Vivihung** [comment]
My project is also facing this issue.
It can be repro in both mobile and desktop safari.
My repro step is:
- clear all the browser cookie/download files/history
- go to my website

Then I can see font icon are missing in my web page.
In safari inspector network tab, there is no network traffic for .woff2.

However, if you refresh the page, the issue will be gone.
(Verified the icon shows up in the page, and see .woff2 was downloaded in inspector)

My repro env info:
iPhone: iOS 10.3 | Mobile Safari 10.0
Mac: Mac OS X 10.12 | Safari 10.1
Fabric: 
"office-ui-fabric-core": "5.1.0",
"office-ui-fabric-react": "2.25.0",

**Comment by Vivihung** [comment]
@ericthompson and @leddie24 ,
Could you please reopen this case? I still can repro it.
I will work with you to repro the issue and find the fix.

**Comment by mikewheaton** [comment]
I'm not able to repro this in Safari for macOS, but I do see the issue on Safari for iOS:
![image](https://user-images.githubusercontent.com/1382445/29690977-1a418b64-88de-11e7-8caf-10957d012e0e.png)

**Comment by Vivihung** [comment]
@mikewheaton I don't know the cable matters for debugging. O.O

I wonder if it's similar to this issue
https://stackoverflow.com/questions/29696700/font-awesome-icon-not-displaying-in-safari-and-ipad
I will try adding cache buster in my PPE env to see if it resolves the issue.

**Comment by mikewheaton** [comment]
@Vivihung Were you able to solve this issue?

**Comment by Vivihung** [comment]
@mikewheaton, thanks for checking back.
After upgrade to 
`"office-ui-fabric-react": "5.1.0"`

And call init icon in app bootstrap
`initializeIcons();`

I cannot repro the issue in iOS.
Will check macOS tonight and reply.

**Comment by Vivihung** [comment]
Not repro in macOS, too.
Feel free to close this issue.

**Comment by mikewheaton** [comment]
I have no idea what changed there, but I'm glad to hear it's working. 😄
