### ISSUE TITLE
Some icons are missing 

### ISSUE THREAD

**Issue by pascalberger** [OfficeDev/office-ui-fabric-core#79]
Some icons are not shown in the sample page. For example ms-Icon--onedrive, ms-Icon--thumbDown, ms-Icon--thumbUp, ms-Icon--officeThreshold, ms-Icon--office365, ms-Icon--office365Preview, etc

**Comment by LezaMax** [comment]
Working on it. I think icons that are not actually part of the release weren't removed from the CSS file. we will correct that soon.

**Comment by Jahnp** [comment]
Yep, this was intentional and has been fixed for the next release. Basically, there were a number of brand-related icons we couldn't include for the release, but which were still used to test with internally. References to those icons have since been removed from the sample icons page. Thanks for the heads-up!

**Comment by andrewconnell** [comment]
Looks like there are a few referenced in the CSS file that aren't there (seems the ones mentioned by @pascalberger were from the pre-1.0 release). The others I've found are: 

- [ms-Icon--dynamicsMarketing](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/dist/css/fabric.css#L3565)
- [ms-Icon--msn](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/dist/css/fabric.css#L3565)
- [ms-Icon--sway](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/dist/css/fabric.css#L3565)

**Comment by sidnc86** [comment]
ms-icon ms-icon--CloudDownload is another css class we are not getting in our Office Addin html page. The icon doesn't render. But on the other hand, ms-icon ms-icon--download does appear. Why does this happen?

**Comment by mikewheaton** [comment]
@sidnc86: Based on the class names, it looks like you're using an older version of Fabric with the previous icon set. What you see documented on [the icons page of the website](http://dev.office.com/fabric#/styles/icons) is the MDL2 icon set. You can tell these icons by the UppercaseNames.

Which version of Fabric are you using?

**Comment by sidnc86** [comment]
Hey @mikewheaton - Thanks for quick and prompt response! We are using Fabric 2.6.0. Here's the URL to the css being referred - https://appsforoffice.microsoft.com/fabric/2.6.0/fabric.min.css

Hope this information helps.

**Comment by mikewheaton** [comment]
Fabric 2.6.0 uses the previous "O365 Icons" set. You can find a list of all the icons in [_Fabric.Icons.scss from the 2.6.2 branch](https://github.com/OfficeDev/office-ui-fabric-core/blob/2.6.2/src/sass/_Fabric.Icons.scss). Hope that helps!
