### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by davidjohnbell** [OfficeDev/office-ui-fabric-core#796]
Hi everyone,
    This might be a newbie thing but I cant seem to find the components page. I am trying to fallow this 
[link](https://github.com/OfficeDev/Office-UI-Fabric/tree/master/src/components/SearchBox) from the Dev Office UI fabric web page > components tab. Im using Visual Studio Community and installed 4.0.0 using the nuget manager. In short, where can I find the components? Thanks in advance!

**Comment by ericthompson** [comment]
Hi, @davidjohnbell - the components have moved over to the [Office UI Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js) repository. There you can find [extensive documentation](https://github.com/OfficeDev/office-ui-fabric-js/tree/master/ghdocs/components) for each component.

Sorry for the confusion here - we're in the final steps of building out and updating our site which should be available in the next 1-2 weeks :smile:

**Comment by davidjohnbell** [comment]
@ericthompson , Wow! whata speedy reply. Youre the best and I think its incredible how Microsoft is putting all of this stuff on the web. Keep up the amazing work.

**Comment by ericthompson** [comment]
Thank you!! Hoping to make even more great stuff available soon!
