### ISSUE TITLE
Documentation site http://dev.office.com/fabric/Button is broken.

### ISSUE THREAD

**Issue by sjclemmy** [OfficeDev/office-ui-fabric-core#802]
The main doc site (e.g. http://dev.office.com/fabric/Button) isn't loading some libraries required for displaying the example html:
`http://dev.office.com/Modules/DevOffice.Fabric/FabricDocs/libs/prism/prism.min.js` returns a 500.
`http://dev.office.com/Modules/DevOffice.Fabric/FabricDocs/libs/js-beautify/beautifyl.js` return a 404.

I'm trying to see some simple examples of required syntax to implement these components but because these two libraries are missing (or at the minimum the beautify library) I can't see the examples.

**Comment by mikewheaton** [comment]
Thanks for reporting this, @sjclemmy. We're investigating and will get the site back up and running as quickly as we can. In the meantime your best option is to [build the Fabric JS website locally](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/BUILDING.md#building-fabric). Sorry for the inconvenience.

**Comment by mikewheaton** [comment]
The issue has been resolved and the site is working well again. 😄
