### ISSUE TITLE
Maximize and Minimize feature request

### ISSUE THREAD

**Issue by vcgupta** [OfficeDev/office-ui-fabric-core#804]
There should be functionality to minimize and maximize the dialog window.

**Comment by ericthompson** [comment]
Hi @vcgupta - could you send us a screenshot and description of your scenario?

**Comment by ericthompson** [comment]
Without any extra info, we're going to go on ahead and close this. If you'd like to reopen, please do so in the [Fabric JS repo](https://github.com/OfficeDev/office-ui-fabric-js) as this is where all of the components that *used* to be a part of this project are now located.
