### ISSUE TITLE
Customization of colors to match existing SharePoint branding

### ISSUE THREAD

**Issue by lafe** [OfficeDev/office-ui-fabric-core#805]
We are using Office UI Fabric to build a SharePoint Add-In which are deployed mostly on premises. As discussed in #783 SharePoint themes are currently not supported. Unfortunately, the customer uses a customized branding (mostly slight color corrections to match it with their own corporate identity).
The customer has the expectation that the new Add-In should match the branding of the existing SharePoint pages. We are currently looking into ways to customize the colors in Office UI Fabric in a way that is compatible with future releases of the Office UI Fabric but were unsuccessful so far. For example, Bootstrap uses the [!default](https://robots.thoughtbot.com/sass-default) identifier to define its own variables, so that it is pretty easy to create a customized experience.
Is there any similar mechanism for Office UI Fabric? Would a pull request that enables a similar behavior to Bootstrap be successful or are those customizations not supported?

**Comment by ericthompson** [comment]
At the moment, we don't have a clear picture of how the Fabric projects interact with SharePoint theming. We've started down the path of supporting this for [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react), but we're still in the early stages of bringing this together.

We're looking into this, and hope to provide an update.
