### ISSUE TITLE
Trying to build 2.6.1 fails on Bundling

### ISSUE THREAD

**Issue by ericthompson** [OfficeDev/office-ui-fabric-core#808]
Cloned down the project and jumped to the 2.6.1 release branch, and tried NPM installing and gulp/gulp watch but get this error:
![image](https://cloud.githubusercontent.com/assets/1420854/18812273/bbd00d00-8283-11e6-87ba-a76c0501a4fd.png)

This keeps you from being able to load and use the localhost docs 😢

**Comment by Jahnp** [comment]
I'll take a look at this.

**Comment by Jahnp** [comment]
I can't repro this from a fresh clone of 2.6.1 using Node 4.2.6 and npm 3.10.7. @ericthompson, did this error crop up on a fresh clone? What versions of Node/npm are you running?

**Comment by ericthompson** [comment]
Hmm - just did a fresh clone myself, npm i, and I'm still seeing the failure.

I ended up running Node v6.2.2 and npm 3.10.7 when I tried at first. I downgraded to the latest stable version of Node, v4.6.0, did a fresh clone, a jump to the new branch (without building with the old dependencies), npm i, and then gulp watch.

Let me leave this issue open while update the V2 documentation to reflect this process.

**Comment by Jahnp** [comment]
So wait--did the error **still** occur after downgrading to Node 4.6.0? Was this on a Mac or Windows? Chances are you won't be the only one to hit this issue--I'd like to repro so it can be fixed. It could be a configuration or syntax issue.

**Comment by ericthompson** [comment]
Sorry about the confusion - updated my comment. It *did* end up working once I downgraded, so I just submitted a PR to update the V2 docs to explain the need for this version of Node.

**Comment by Jahnp** [comment]
Gotcha. In that case, I'd rather take a crack at a patch rather than forcing users to snap to an older version of Node :) Let's update the docs in the short term, but I'll try to get a fix out today or tomorrow if possible.

**Comment by ericthompson** [comment]
Sounds good. Really looks like we should update some of these docs to explain how to view the localhost docs in a more primary way as this is the only way to see the live samples. I agree with you - let's get the updated docs in now to unblock folks now, and then get a patch in soon. Thanks for your help!

**Comment by Jahnp** [comment]
Totally agreed on both fronts. I'll try to get that patch out soon.

**Comment by ericthompson** [comment]
Fixed by [this release - 2.6.2](https://github.com/OfficeDev/office-ui-fabric-core/releases/tag/2.6.2). I'll go in and revert my statement in the md file and we can call this closed 😄
