### ISSUE TITLE
Adjustable Left Navigation Bar with Icon 

### ISSUE THREAD

**Issue by JyotsnaWadhwani** [OfficeDev/office-ui-fabric-core#809]
Hi,
I am looking for a left navigation bar which can maximize and minimize. We can navigate via the left navigation bar when it is minimized with the help of Icons on it. I am attaching 2 screenshots which will help you understand what I am looking for. Please let me know if you guys are planning for any such thing related to it in your future releases.
![untitled12](https://cloud.githubusercontent.com/assets/20122732/18825526/87d8113c-83e6-11e6-9a05-a6ff0377216a.png)
![untitled13](https://cloud.githubusercontent.com/assets/20122732/18825539/9e0602fc-83e6-11e6-87d5-459a2829e46e.png)

**Comment by JyotsnaWadhwani** [comment]
Adding a few more screenshot
![untitled14](https://cloud.githubusercontent.com/assets/20122732/18829483/12362086-83fa-11e6-946f-4e84126fdaf0.png)
![untitled15](https://cloud.githubusercontent.com/assets/20122732/18829490/15bc1f62-83fa-11e6-891a-2d4b167359de.png)

**Comment by ericthompson** [comment]
Thank you for the request, @JyotsnaWadhwani. I've [put a card on the Trello board](https://trello.com/c/vd87zQM6/30-collapsing-left-nav-with-icons-component) to reflect it. Please give it an upvote so we can track what folks want.

Thanks!

**Comment by ericthompson** [comment]
@JyotsnaWadhwani - I've added the request to the [Fabric JS Trello board](https://trello.com/b/wq7oIK87/office-ui-fabric-js-requests) - this is the board that tracks requests for the component set that *used* to be a part of this project ([Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js)). Is this the component set you are asking for this to be included in or were you hoping that this be a part of the [Fabric React (React-based) component set](https://github.com/OfficeDev/office-ui-fabric-react)?

**Comment by JyotsnaWadhwani** [comment]
I am hoping that it will be a part of the Fabric JS component.

**Comment by ericthompson** [comment]
Gotcha - thanks!

**Comment by gsandorx** [comment]
Hello, did this ever got implemented?
