### ISSUE TITLE
Unable to center spinner

### ISSUE THREAD

**Issue by vivmaha** [OfficeDev/office-ui-fabric-core#811]
It is not possible (elegantly) to horizontally center the spinner within its parent div. 

`ms-Spinner`'s css only specifies a height, not a width. This prevents horizontal centering.

To work around this, I've hard coded the width myself.

**Comment by mikewheaton** [comment]
Thanks for bringing this to our attention, @vivmaha. If you have a solution that's working we'd love a pull request into the [Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js) project. 😄
