### ISSUE TITLE
Icon name typo: CheckMark

### ISSUE THREAD

**Issue by mimisasouvanh** [OfficeDev/office-ui-fabric-core#816]
I tried checkmark, checkmark, and CheckMark and neither of those work. When I tried "check" it works.
Not sure if the icon names are changed for each version ie 2.1.0 vs 2.6.1, but it needs to be fixed here: http://dev.office.com/fabric#/styles/icons

**Comment by ericthompson** [comment]
Hi, @mimisasouvanh - the site currently shows the new iconography available in the latest versions of Core, JS, and React implementations. For the previous version of the iconography, you can follow these instructions to build and host the 2.6.X documentation site where you can see all of the icons and their appropriate class names:

1. Clone the the Core project
2. Checkout the branch for the 2.6.1 release: `git checkout release/2.6.1` from the command line
3. Navigate to the folder that contains the gulpfile.js file (Fabric's root)
4. `npm install`
5. `gulp watch`

Navigating to localhost:2020, you can check out this page:
![image](https://cloud.githubusercontent.com/assets/1420854/19204260/9c8963e4-8c90-11e6-8f07-9fbb401b563a.png)
