### ISSUE TITLE
Missing Icon: CalendarMirrored

### ISSUE THREAD

**Issue by vinny75** [OfficeDev/office-ui-fabric-core#817]
The Office Fabric UI site shows a CalendarMirrored icon but using the latest version of Fabric Core, it does not display.  Tried searching the repository for CalendarMirrored as well and nothing.  Is this icon available in core?

**Comment by ericthompson** [comment]
We've actually removed all mirrored icons in favor of using flipping to accommodate our RTL scenarios - you can see the work in [this pull request](https://github.com/OfficeDev/office-ui-fabric-core/pull/792). We had a [subsequent PR that fixed some of these still appearing in the SCSS](https://github.com/OfficeDev/office-ui-fabric-core/pull/795).

This is a bit easier, allows us to remove a good number of icons (for less bloat), and doesn't degrade the quality as these icons were exactly mirror images (vs. being redrawn specifically for RTL).

[It definitely looks like these are still showing up on the site](http://dev.office.com/fabric#/styles/icons) - we'll look into getting this update asap.

**Comment by ericthompson** [comment]
This is now fixed in the newest version of the site - please do a hard refresh if you're still seeing the old icons.
