### ISSUE TITLE
Icon Name Typo: CarotRightSolid8

### ISSUE THREAD

**Issue by vinny75** [OfficeDev/office-ui-fabric-core#818]
Believe it should be CaretRightSolid8 to match CaretLeftSolid8

**Comment by ericthompson** [comment]
You are quite right! This is actually in the process of being fixed at the moment, and is just taking some time to make it to our CDN.

Good catch 😄

**Comment by vinny75** [comment]
Well, that is odd, searching just 'Carot' doesn't show the existing issue but searching for 'CarotRightSolid8' - either way, glad it's being fixed!
