### ISSUE TITLE
Check-in icon

### ISSUE THREAD

**Issue by Abrissirba** [OfficeDev/office-ui-fabric-core#820]
I'm writing an add-in for SharePoint and need an icon for checking-in/out a file but doesn't seem to find any suitable at http://dev.office.com/fabric#/styles/icons.

**Comment by ericthompson** [comment]
Hmm... I've seen some that may work. Would this just be a for a generic file? Also, do you have a specific metaphor in mind?

The one that I've seen (that's generic) is this:
![image](https://cloud.githubusercontent.com/assets/1420854/19223452/47e213ae-8e25-11e6-892b-3b4d90dff2c9.png)

That would signify checked out with the "checked in" version being:
![image](https://cloud.githubusercontent.com/assets/1420854/19223465/910e30e4-8e25-11e6-8968-e7a6a0ff16d2.png)

**Comment by Abrissirba** [comment]
It is fine with a generic version to start with. The check out icon is fine but I can't find it on the doc site. 

I think that the same icon but with the arrow at the opposit direction would be fine for the action to check-in a document.

**Comment by ericthompson** [comment]
Yep, that's not currently in our icon set, but I've just filed a request for it to be added. I'll also look into a "checked in" version too. Keeping this open until we get font file up.

**Comment by mikewheaton** [comment]
A new icon, `PageCheckedIn`, was included in #828. This will be part of the next release of Fabric Core which is expected out very soon.

Here's what it looks like:

![screen shot 2016-11-03 at 1 57 54 pm](https://cloud.githubusercontent.com/assets/1382445/19984905/8ccb5136-a1cd-11e6-99b9-699711d06353.png)
