### ISSUE TITLE
2.6.2 is not available on NuGet

### ISSUE THREAD

**Issue by rolandoldengarm** [OfficeDev/office-ui-fabric-core#824]
Why has version 2.6.2 only been published to npmjs, and not to NuGet? Now they are out of sync, causing issues: https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/424

**Comment by Jahnp** [comment]
Ah, we must have missed that when publishing the release. There is no difference in the output between 2.6.1 and 2.6.2, but for the sake of dependency resolution (and common sense) we'll publish 2.6.2 to NuGet as well. Stay tuned--we'll update this issue when we have that fixed. Thanks for filing @rolandoldengarm!

**Comment by Jahnp** [comment]
2.6.2 has now been [published to NuGet](https://www.nuget.org/packages/OfficeUIFabric/2.6.2), so closing for now. Please let me know if you run into any further issues.
