### ISSUE TITLE
Dropdown scrolling issue (2.6.1-2.6.2)

### ISSUE THREAD

**Issue by usaalex** [OfficeDev/office-ui-fabric-core#826]
Trying to use dropdown component and scrolling doesn't work even in example. Instead the whole page is scrolling, Tried to make body overflow hidden, but still .ms-Dropdown-items not scrolling to an active item.
![image](https://cloud.githubusercontent.com/assets/12829510/19626400/c54dd412-9939-11e6-80f6-ceb3dcb5fd4c.png)
Tested both in IE and Chrome.

**Comment by mikewheaton** [comment]
I'm not having any trouble scrolling through the dropdown items. Here's a screen capture:

![demo of scrolling a dropdown](https://cl.ly/1V0A3i2K210T/Screen%20Recording%202016-10-28%20at%2012.35%20PM.gif)

The page scrolls once I've reached the top or bottom of the dropdown, but until that point the dropdown scrolls correctly.

**Comment by mikewheaton** [comment]
I'm going to go ahead and close this issue as we're not able to repro it. Please reopen the issue if you have more details to help us troubleshoot this.

**Comment by poojashivach** [comment]
Scenario- Dropdown in having 50 options to select from.

While incorporating Dropdown component of office UI fabric, If I reduce the size of portion in which Dropdown will render scrollbar does not appear.

I am following this link - https://codepen.io/andrewconnell/pen/RWGNON?editors=1000 

![dropdown issue](https://cloud.githubusercontent.com/assets/25025542/21924630/fd109384-d99f-11e6-8197-769351c7bccd.png)

If width is increased for task pane scrolling works.
![working solution](https://cloud.githubusercontent.com/assets/25025542/21924692/35b1c0b4-d9a0-11e6-85fc-688483dd7b47.png)

can you please help me with it?

**Comment by mikewheaton** [comment]
I've opened a new issue in the Fabric JS repo and assigned it to myself: https://github.com/OfficeDev/office-ui-fabric-js/issues/271
