### ISSUE TITLE
Color editing icons

### ISSUE THREAD

**Issue by Abrissirba** [OfficeDev/office-ui-fabric-core#827]
I would like to request icons for setting background color and border color

**Comment by ericthompson** [comment]
I've created [one card for each](https://trello.com/c/uuKCNXao/19-background-color) [of the two requests](https://trello.com/c/pwg4rE52/20-border-color).

Do you have any examples of metaphors that would work for you?

**Comment by Abrissirba** [comment]
something like the color icons here: https://material.io/icons/

**Comment by mikewheaton** [comment]
Which icon in particular from there are you looking for something similar to?

**Comment by Abrissirba** [comment]
"border color" and "format color fill"

**Comment by ericthompson** [comment]
@Abrissirba - we meant from the materials link. It's tough to find a metaphor that works as a monochrome symbol.

Some examples exist in standard Office apps, but they utilize multi-color to be recognizable (along with labels):
<img width="121" alt="screen shot 2016-11-04 at 7 50 07 am" src="https://cloud.githubusercontent.com/assets/1420854/20009862/4fbd8e08-a263-11e6-8325-2ce0d448c5b1.png">

Just wanted to get a sense of what kinds of metaphors you're looking for or that work for you.

**Comment by ericthompson** [comment]
After poking around, we've found a paintbrush that you could then use in conjunction with other symbols/text. Would this suffice?

![image](https://cloud.githubusercontent.com/assets/1420854/20450790/06059332-ada8-11e6-944d-9f44c99bf763.png)

**Comment by mikewheaton** [comment]
I'm going to close this issue for now, as we haven't heard back.
