### ISSUE TITLE
Scope all mixins and variables, and name them consistently

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#832]
Here are some mixins we currently have:

```
ms-u-borderBox
ms-baseFont
ms-Grid
high-contrast
ms-Icon--s
brandIconClasses
```

We should prefix all of our mixins with `ms-` so that they can be safely used in other projects without conflicts, and settle on whether we want to use camelCase or kebab-case. Thoughts?

**Comment by Jahnp** [comment]
Yes, completely agreed on consistency--thanks for being proactive here. I know that we *were* consistent for some time on this and even scheduled work to do so, but seems we've fallen off a little. I'd be fine sticking with camelCase since that's a little more prevalent than kebab-case, but I don't feel super strongly about it.

**Comment by mikewheaton** [comment]
Agreed, I prefer camelCase as well and it's what we use throughout Fabric.

My suggestion is:
- start every mixin with the `ms-` prefix for safety
- if the purpose of a mixin is to output a class, match the mixin name and capitalization to the class (e.g. `@mixin ms-Grid` produces `ms-Grid`, `@mixin ms-u-borderBox` produces `ms-u-borderBox`)
- if the mixin is used internally and does not produce a class directly, give it a simple camelCase name (e.g. `ms-brandIconClasses`)

**Comment by ericthompson** [comment]
This could also be done at the same time as #349.

**Comment by mikewheaton** [comment]
I've changed the title to reflect that we also have inconsistent variable names. For example `ms-font-size-m` and `ms-color-neutralLight`. While we're introducing breaking changes, it might be a good time to clean this all up as well.

**Comment by mikewheaton** [comment]
A few mixins have been renamed in #868, but I'll be doing most of this in another PR.
