### ISSUE TITLE
Font issue: Add icon looks terrible at 14px but ok at 15px.

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-core#835]
ContextualMenu and CommandBar seem to use 14px, which looks like this:

![image](https://cloud.githubusercontent.com/assets/1110944/20090460/104381b0-a542-11e6-960a-4e281c476f88.png)

If I bump it to 15px (or 17 or 19 but not 13) it is clear:
![image](https://cloud.githubusercontent.com/assets/1110944/20090476/275d5858-a542-11e6-857c-c2ad486942a3.png)

But then the Upload icon has the opposite effect (clear at 14, blurry at 15...)

Anything that can be done at the font level? It's really ugly.

**Comment by trasmu** [comment]
Yes, there are certain sizes that the icons are intended to be displayed. As they have been hinted at those sizes.

**Comment by dzearing** [comment]
The problem I have is that I'm cool if 14px looks consistently good for all icons, but 15 doesn't. But as it is, they *aren't consistent*! So that would force us downstream to do some really nasty weird hacks to work around. I don't htink this is a fabric-react issue at all.

**Comment by dzearing** [comment]
It is not acceptable to force some icons to 14px and others to 15px at a css layer just to work around font bugs.

**Comment by trasmu** [comment]
My point is that there is a specific size that the icons are intended to be used at.

I believe that size is 20px.

**Comment by dzearing** [comment]
@trasmu possible to add hints for the common points? (e.g. if we agree we need 14px size, could we get a hint for that size?)

**Comment by ericthompson** [comment]
After checking with our icon team, almost all icons are optimized for 16px (with a few exceptions that are called out in the friendly name).

Adding new hints is not something they're currently planning to do, so we should be massaging the sizes to find what works best.

**Comment by chenxinyanc** [comment]
I come here because I have saw similar effect on the toolbar.

https://codepen.io/xinychen/pen/rNNMBzE

![image](https://user-images.githubusercontent.com/50703224/66991000-cdb19100-f0f9-11e9-91c7-71f91105a82b.png)

Note the "Add" and "Remove" icon looks slightly blurry. All the icons are in 16px font-size. This is frustrating because blurry icons are not acceptable, and I will have to replace these specific icons with its SVG counterpart.
