### ISSUE TITLE
feature request for trello board: Treepanel

### ISSUE THREAD

**Issue by Vaevictus** [OfficeDev/office-ui-fabric-core#839]
I would like to request a treepanel implementation, highly configurable with nodes that can load data async, fire events on click/expand etc.
The ExtJS tree is the best one I've seen and no other framework comes close, hoping that fabric can beat it.

**Comment by mikewheaton** [comment]
We've received requests for a [TreeView/accordion component](https://trello.com/c/hpLEICo1). Would that be equivalent to the [ExtJS TreePanel](http://docs.sencha.com/extjs/4.2.1/#!/api/Ext.tree.Panel) you mentioned?

**Comment by mikewheaton** [comment]
Closing as we haven't heard anything in the last month. Please feel free to re-open this if you have more details on what you'd like.
