### ISSUE TITLE
docs datepicker doesn't fit within frame

### ISSUE THREAD

**Issue by ichpuchtli** [OfficeDev/office-ui-fabric-core#841]
PickaDate.js
![image](https://cloud.githubusercontent.com/assets/1134912/20293198/ef697b8a-ab3f-11e6-87a8-e58bbc3c98d6.png)

https://dev.office.com/fabric#/components/datepicker

**Comment by mikewheaton** [comment]
Thanks for reporting this, @ichpuchtli. The DatePicker example you see on the Fabric website is from the [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react/) project. There's an [open issue there](https://github.com/OfficeDev/office-ui-fabric-react/issues/355) for this.
