### ISSUE TITLE
Dropdown does not open on Android Chrome, the page scroll position jumps to the top and back down

### ISSUE THREAD

**Issue by sompylasar** [OfficeDev/office-ui-fabric-core#856]
Please see the attached screen recording video (gif). The jump happens when I tap the dropdown control.

![screenrecord_2016-11-29-07-40-15](https://cloud.githubusercontent.com/assets/498274/20716880/8e4e098c-b608-11e6-8912-018385d665a6.gif)

**Comment by ericthompson** [comment]
@sompylasar - is this a question about components in the [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react) project?

**Comment by sompylasar** [comment]
@ericthompson Yes. Sorry, wrong repo. I'll repost there. Thank you.

**Comment by ericthompson** [comment]
No worries 😄

**Comment by sompylasar** [comment]
Just for reference: https://github.com/OfficeDev/office-ui-fabric-react/issues/626
