### ISSUE TITLE
Sliver bar control UI element not vertically centered. -2px

### ISSUE THREAD

**Issue by chiubacca** [OfficeDev/office-ui-fabric-core#857]
![slider](https://cloud.githubusercontent.com/assets/7328988/20729387/a1700820-b636-11e6-82bd-5b169da01b94.png)

It renders +2px too far up in Safari and Chrome on Mac Desktop.

**Comment by ericthompson** [comment]
@chiubacca - is this a question about components in the [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react) project?

**Comment by chiubacca** [comment]
Hi, it's based on what I saw here: https://dev.office.com/fabric#/components/slider

**Comment by ericthompson** [comment]
Gotcha. Could you please [file an issue in the Fabric React repository](https://github.com/OfficeDev/office-ui-fabric-react/issues/new)?

This repository is the Core which includes all of the main styling (colors, grid, icons, fonts, etc.).
