### ISSUE TITLE
Use the ms-Fabric wrapper to apply localized font families

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#867]
Right now we have a huge selector for each language override, which targets all of the `ms-font-` classes that have a parent with the `lang` attribute set. Those look like:
```
*[lang='tha'] .ms-font-mi, *[lang='tha'] .ms-font-xs, *[lang='tha'] .ms-font-s ... {
  font-family: 'Leelawadee UI', 'Kmer UI', 'Segoe UI WestEuropean', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif;
}
```

Bloat aside, this only works so long as *every piece of text has an `ms-font-` class on itself or a parent*. When mixins are used (like we do in Fabric React components) these classes aren't output and the correct fonts aren't applied.

Suggestion: Let's use the `ms-Fabric` wrapper class to set the font family. This can be overridden with a single selector for each language:

```
.ms-Fabric[lang='tha'] {
  font-family: 'Leelawadee UI', 'Kmer UI', 'Segoe UI WestEuropean', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif;
}
```

We could also support using the `lang` attribute on the root `html` element:
```
html[lang='tha'] .ms-Fabric {
  font-family: 'Leelawadee UI', 'Kmer UI', 'Segoe UI WestEuropean', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif;
}
```

**Comment by Jahnp** [comment]
This would be a GREAT improvement! I'm especially a fan of the second proposal, using `lang` on `html`, since this maps to how most apps in our ecosystems are used today. Providing both as options would be great as well.

**Comment by mikewheaton** [comment]
After a closer look, this is the same ask as #382. Closing this as a duplicate.
