### ISSUE TITLE
Remove and rename icons

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#879]
We've been asked to remove the "CollabsDBLogo" and "AlchemyLogo" icons, and to rename "AppForOfficeLogo" to "OfficeAddins".

To do:
[ ] Have these changes made to the icon font.
[ ] Update Fabric with the latest icon font. This is a breaking change and will require a **major release**.
[ ] Verify that the website shows the icons correctly, particularly on the [brand icons page](http://dev.office.com/fabric#/styles/brand-icons).

**Comment by Jahnp** [comment]
I think this can be closed since #910 has been merged.
