### ISSUE TITLE
Remove `borderColorTop` classes

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#886]
We have two classes that were added in by special request a long time ago:

```
.ms-borderColorTop-themePrimary,
.ms-borderColorTop-themePrimary--hover:hover {
  border-top-color: #0078d7;
}
```

These have never been documented, and there's a good chance they're no longer in use. I'd suggest we remove this and recommend developers use the SCSS variables to make classes like this local to their project.

**Comment by Jahnp** [comment]
This sounds reasonable. I know those classes were used in the OWA Calendar view to pick up the user theme, but I'm not sure if they're still in use, or if that will continue to be the case. I'm also not sure that they're even using Fabric as a direct dependency, meaning this change might not affect them. 

I'd say as long as we follow up with them to make sure they can plan for this, we should be fine to remove them.
