### ISSUE TITLE
Continuous Integration via Travis for Bower/NPM

### ISSUE THREAD

**Issue by Jahnp** [OfficeDev/office-ui-fabric-core#89]
Fabric should have CI in place for testing and deploying builds to Bower/NPM.

**Comment by mikewheaton** [comment]
I'm not sure what would be involved here or who could do the work. Let's discuss.

**Comment by andrewconnell** [comment]
Check out how the Angular Material guys do it (http://github.com/angular/material). This is how we’re modeling our CD with https://github.com/ngOfficeUIFabric/ng-officeuifabric. I’m doing it for ngofficeuifabric… it’s a WIP now and somewhat automated locally with scripts that will eventually get added to the main project.

When we do a push to the master branch (only on master), on a green build in travis, a script will run that tags the current version with the version in package.json, builds the library (minified & unminified), updates the repo we use for deployment to npm/bower/cdnjs/nuget & tags it with the version & then publishes to npm/nuget.

All that’s required is a green build push to mater that triggers everything else in an automated way.
