### ISSUE TITLE
Remove font weight hover classes

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#894]
We have a set of classes that are used to set the `font-weight` of text when that text is hovered on:
- `.ms-fontWeight-light--hover`
- `.ms-fontWeight-semilight--hover`
- `.ms-fontWeight-regular--hover`
- `.ms-fontWeight-semibold--hover`

Are these useful? If so, let's document them on the [typography page of our website](http://dev.office.com/fabric#/styles/typography) and, if not, let's remove them.

**Comment by Jahnp** [comment]
I don't recall when these were added or what they were added for, but changing font-weight on hover seems... not great. I also believe that in general, we aren't using this pattern in product. I'd be inclined to deprecate in the next minor/patch release and remove in 7.0.
