### ISSUE TITLE
Remove mixin: ms-input-placeholder()

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#896]
`input-placeholder` is [fully implemented](http://caniuse.com/#search=input-placeholder) in the browsers we support, so the `ms-input-placeholder()` mixin is no longer necessary. Even if prefixes were required, that is best left to Autoprefixer rather than a mixin.

**Comment by Jahnp** [comment]
Makes sense to me. Let's gut it!
