### ISSUE TITLE
Build error: 'stack level too deep'

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#898]
The build is failing roughly half of the time with errors like:

```
[12:14:20] Error in plugin 'SASS compiler'
Message:
     /Users/mike/Sites/Microsoft/office-ui-fabric-core/src/sass/_Icon.scss442: line 45, col No Code, code src/sass/_Icon.scss
SystemStackError: stack level too deep
                   on line 442 of src/sass/_Icon.scss
>> s-Icon--PowerPointLogo::before { @include ms-Icon--PowerPointLogo; }
   ------------------------------------------^
, undefined
```

Any ideas, @battletoilet?

**Comment by DustinDSchultz** [comment]
I'm getting this issue all of a sudden as well at various @includes throughout my project.

**Comment by mikewheaton** [comment]
This seems to be caused by the use of `@content` in [Fabric.Scoped.scss](https://github.com/OfficeDev/office-ui-fabric-core/blob/master/src/sass/Fabric.Scoped.scss). When I comment out the call to `@include scope-fabric` I'm unable to repro this issue.

Others seem to have had luck with [downgrading NPM packages](https://github.com/jtangelder/sass-loader/issues/340#issuecomment-271399145) so I'll take a look at the `gulp-sass` package and see if any changes there could be the culprit.

**Comment by mikewheaton** [comment]
After forcing an updating to [gulp-sass 3.1.0](https://github.com/dlmanning/gulp-sass/releases/tag/v3.1.0), I've now run 10 builds without any errors. It's hard to know for sure if this fixes this issue as it was intermittent, but we should be using the latest version anyway so I'll submit a PR.
