### ISSUE TITLE
Want you to make a plugin for Sketch.app

### ISSUE THREAD

**Issue by bino98** [OfficeDev/office-ui-fabric-core#903]
I always use it conveniently. Thank you for Office UI Fabric teams.

I would like to do UI design using Sketch.app. but, There is no good plugin...
I am planning to make it if I am told that I can make it myself, but if anyone is making a person I would like you to tell me.

**Comment by mikewheaton** [comment]
Would you primarily be interested in text styles and colors, or in components (e.g. radio buttons, dropdowns)?

**Comment by bino98** [comment]
@mikewheaton 
yes. I am mainly looking for a plugin that represents UI components.

**Comment by mikewheaton** [comment]
I've added your request to the Trello board where we track potential new features and resources: https://trello.com/c/qIUxUpOa

**Comment by bino98** [comment]
@mikewheaton 
Thank you for writing to Trello board 👍

**Comment by Russolini** [comment]
Please create this.  I'm ready.....adbove XD is ok, but Sketch is really where a lot of designers spent their time.
