### ISSUE TITLE
Update ms-background-gradient() mixin to correct syntax

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#904]
The [ms-background-gradient() mixin](https://github.com/OfficeDev/office-ui-fabric-core/blob/master/src/sass/mixins/_General.Mixins.scss#L20) currently outputs:

`background-image: linear-gradient(left, ...`

When the [correct syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient) would be:

`background-image: linear-gradient(to left, ...`

I propose we keep passing in a simple string ("left", "right", "top left", etc.) and then use the mixin to add the "to".

**Comment by Jahnp** [comment]
Makes sense to me.

**Comment by mikewheaton** [comment]
Unfortunately, it's not as simple as adding "to" because that changes the direction:

![image](https://cloud.githubusercontent.com/assets/1382445/24674751/80de17f6-1931-11e7-93db-193187075fe9.png)

In order to keep the existing parameters and not introduce a breaking change, we need to swap directions within the mixin (e.g. left becomes right). This way the result matches our current mixin:

![image](https://cloud.githubusercontent.com/assets/1382445/24674797/a4497ef6-1931-11e7-8265-212788bc8515.png)

This can all be seen in the [CodePen demo](http://codepen.io/mikewheaton/pen/jBREpK?editors=1100).
