### ISSUE TITLE
Remove 'ms' prefix from local variables in mixins

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#905]
Many of the mixins use the `ms-` prefix for local variables, like so:

```
// Drop shadow.
@mixin ms-drop-shadow($ms-x-offset: 0, $ms-y-offset: 0, $ms-blur: 5px, $ms-spread: 0, $ms-alpha: 0.4) {
  box-shadow: $ms-x-offset $ms-y-offset $ms-blur $ms-spread rgba(0, 0, 0, $ms-alpha);
}
```

This is unnecessary, as the prefix is there to prevent conflicts with other global variables. Removing these won't affect the usage of mixins or the output.

**Comment by Jahnp** [comment]
This is totally righteous. The `ms-` prefixes just add noise in this context and make it hard to separate from the global values we expose. Yes, they should definitely go for parameters & local definitions.
