### ISSUE TITLE
Set -ms-high-contrast-adjust within ms-Fabric wrapper

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#907]
Edge has a new feature that sets a black background color for all text in high contrast mode. While this is generally a helpful thing to do, in Fabric we apply our own high contrast styles that can conflict with the default background color.

To prevent Edge from interfering in our high contrast styles, we can add `-ms-high-contrast-adjust:none;` to the ms-Fabric wrapper class.

**Comment by mdahamiwal** [comment]
@mikewheaton this is still not fixed, can we investigate ?

**Comment by mikewheaton** [comment]
@mdahamiwal Sure, send me an email or IM and I can take a look.

**Comment by mdahamiwal** [comment]
Hello @mikewheaton, as discussed offline the update for core 7 is still pending and we would need a lot more testing before we move to that. Meanwhile to fix the HC styling issues in VSTS, I have raised a PR https://github.com/OfficeDev/office-ui-fabric-react/pull/1718. Let me know if you see any issue.
