### ISSUE TITLE
Fabric UI kit design source files

### ISSUE THREAD

**Issue by ganeshprabhun** [OfficeDev/office-ui-fabric-core#908]
Would be great if we could get access to Fabric UI kit source files in Photoshop / Sketch or Illustrator.

**Comment by Jahnp** [comment]
Hey @ganeshprabhun, so sorry for the delay here. This is something we're working on and should have news to share before long. Thanks!

**Comment by revunitbrian** [comment]
It would also be great to include the Segoe font family and icon fonts along with the sketch files.

**Comment by Jahnp** [comment]
Wanted to give a quick update here: we're actively working on these, but have a lot of legal hurdles related to the assets that we're trying to wrangle. Watch this space--we'll keep it updated when we have some news.

**Comment by mikewheaton** [comment]
There is now an Adobe XD toolkit available on the Resources page: https://developer.microsoft.com/en-us/fabric#/resources

**Comment by geekpulp** [comment]
@mikewheaton any eta on a sketch toolkit too?

**Comment by Javabird919** [comment]
How about for Figma, too, please!

**Comment by mdtauk** [comment]
Is this not now FluentUI Web?
https://www.figma.com/community/file/836828295772957889

**Comment by Javabird919** [comment]
@mdtauk, yes it is, thanks! I was specifically looking for SVG version of the icons [found here](https://uifabricicons.azurewebsites.net/#how-to-use-the-tool). This link provides unicode and name, but not SVG (the "glyph" option isn't SVG).
