### ISSUE TITLE
Rendering of headers of nested groups in Grouped List Office UI

### ISSUE THREAD

**Issue by ujavai2s** [OfficeDev/office-ui-fabric-core#916]
Hi all,

I am trying to use grouped List from Office UI. It is working perfectly except rendrening of group header which is partially working. I am using function {onRenderHeader} to optimize group header. It is working for header of top group level but not working for headers of nested groups. {onRenderCell} is working only for items. Is there any solution or any way to render header of nested groups?
Best Regards

**Comment by Jahnp** [comment]
Hi @ujavai2s, it sounds like you're having an issue with the Fabric React List component. Did you intend to open this in [that repo](https://github.com/OfficeDev/office-ui-fabric-react/issues)? If so, would you mind re-opening there? I'll go ahead and close this for now, but feel free to re-open if I got that wrong.
