### ISSUE TITLE
Headset icon is missing in CDN 4.1.0

### ISSUE THREAD

**Issue by Vivihung** [OfficeDev/office-ui-fabric-core#917]
I'm using this CDN
https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/4.1.0/css/fabric.min.css

And try to use the icon with this html
`<i class="ms-Icon ms-Icon--Headset"></i>`

But the Headset icon doesn't show. And I couldn't find it in fabric.min.css either.

**Comment by mikewheaton** [comment]
The Headset icon was added in PR #858, which was included in the [5.1.0 release](https://github.com/OfficeDev/office-ui-fabric-core/releases/tag/5.1.0). Once you update to that version or newer, the `ms-Icon--Headset` class should work as expected.

**Comment by Vivihung** [comment]
Thanks! I've updated the CDN link to 5.1.0 and it works!
https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/5.1.0/css/fabric.min.css
