### ISSUE TITLE
ms-button style has no prefix

### ISSUE THREAD

**Issue by artemsaveliev** [OfficeDev/office-ui-fabric-core#918]
The issue comes up when creating a cross-platform button component (which works with and without fabric)
Directly using ms-button style is not scoped to ms-fabric, and the style gets applied even if button does not have ms-fabric parent.

**Comment by Jahnp** [comment]
Hi @artemsaveliev, to be clear, are you talking about the Button component from [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react) or [Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js/)?

Also, could you expand a little on the issue you're seeing? I'm not sure I fully understand what you're trying to accomplish and what exact issue you're seeing with button styles. In general, Fabric component class names (e.g. `ms-Button`) are not intended to be scoped under the `ms-Fabric` wrapper class.

**Comment by artemsaveliev** [comment]
@Jahnp I am trying to use ms-Button class in my control, i.e.
<control class="myStyle ms-Button" />
This control is used on fabric pages and on non-fabric pages. Both types of pages unfortunately link to fabric (it's a product-wide stylesheet). 

Basically, I need the button styling to only apply when it's used in fabric context. Currently it's impossible - the only way to achieve this, is to not include fabric css at all (and not feasible for me, as it's product-wide link).

**Comment by Jahnp** [comment]
Gotcha. There might be some options for you based on current and upcoming work but I'd want to know the specifics of your situation before recommending a particular path. I didn't realize you were a MS employee--I'll follow up offline about your specific scenario and we can report back here once resolved.

**Comment by mikewheaton** [comment]
Seems that this has been resolved outside of GitHub and, in any case, it should be filed under Fabric JS or Fabric React if it is an issue. Closing.
