### ISSUE TITLE
ms-dropdown options not displayed properly

### ISSUE THREAD

**Issue by ashaysk** [OfficeDev/office-ui-fabric-core#920]
Hello, I am trying to create ms-dropdown on a taskpane for office excel. The issue I am facing is the options in the select are displayed in the right corner of the taskpane and is not attached to textfield. I am attaching an image of what is happening when I make a selection. Does anybody have any insights on how to fix this? I am using office fabric 2.6.0
![dropdown](https://cloud.githubusercontent.com/assets/13885101/23119839/d5f21d88-f77f-11e6-96db-b35a74a5fd5d.png)

**Comment by mikewheaton** [comment]
While we generally don't support the components from 2.6.x releases of Fabric – please see the [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react) and [Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js) projects for supported component sets – we made an exception in this case and released [version 2.6.3](https://github.com/OfficeDev/office-ui-fabric-core/releases/tag/2.6.3) with a patch for that issue. 😄
