### ISSUE TITLE
Link to scoped icon font file is incorrect

### ISSUE THREAD

**Issue by Jahnp** [OfficeDev/office-ui-fabric-core#922]
Right now, the path to the scoped icon font file in fabric-6.0.0.scoped.css (https://static2.sharepointonline.com/files/fabric/assets/icons/fabricmdl2icons-6.woff2) is incorrect. It should instead point to https://static2.sharepointonline.com/files/fabric/assets/icons/scoped/fabricmdl2icons-6.woff2.

**Comment by mikewheaton** [comment]
Fixed by #923
