### ISSUE TITLE
Checkbox no check icon anymore after updated the Office UI Fabric version to 2.6.3

### ISSUE THREAD

**Issue by jbranders** [OfficeDev/office-ui-fabric-core#924]
The icon for the checkbox tick is gone after updating the version of the Office UI Fabric. 
![image](https://cloud.githubusercontent.com/assets/16958349/23301926/aae90ede-fa8c-11e6-9108-dc58b571e97c.png)

What do i wrong or have i the wrong version? 

**My Code:**
```
<div class="ms-ChoiceField">
                <input id="demo-radio-selected" class="ms-ChoiceField-input" type="checkbox" checked="checked">
                <label for="demo-radio-selected" class="ms-ChoiceField-field">
                    <span class="ms-Label">Selected</span>
                </label>
            </div> 
```

**Comment by Danny-Engelman** [comment]
What version(s) are you loading?  Core? React? FabricJS?
Check the network tab, find the fabric css files (components as well) and read the version info in the header.  
And what is the **full** pathname of the fabricmdl2icons*.woff file loaded?

**Comment by jbranders** [comment]
I'm loading Core, but i cannot find the version in the header of the request.

**Comment by Danny-Engelman** [comment]
Not the header, the CSS contents, so you need to look at the response.
You can also right-click in the network Tab and 'Open in new tab' (note the uri will also show the version nr)

**Comment by jbranders** [comment]
I'm using Office UI Fabric 2.6.3, but what i notice is that i use also the icon .ms-Icon--Edit and that's gone to. Very strange.

**Comment by Danny-Engelman** [comment]
2.6.3 was a patch for 2.6.2 .. which was the october 2016 release

Alas 2.6.3 is now listed first on the releases page: https://github.com/OfficeDev/office-ui-fabric-core/releases

Major changes since 

Current version Fabric Core is 6.0.0 , that is the second one on the release page
https://github.com/OfficeDev/office-ui-fabric-core/releases

Be sure to read the release notes. 6.0.0 changed Class notation ``ms-u`` notation to ``ms-``

**Comment by jbranders** [comment]
I don't understand it, i use ms-Icon--Edit, but now after the update it's gone? Why the icons are removed?

**Comment by Danny-Engelman** [comment]
I can't (or rather won't) check 2.6.3

``ms--Edit`` is available in 5.0.1 , 5.1.0 and 6.0.0 for sure

So you either are still using and old version or you made a typo, or you did something else wrong

If you are taking Icon names from Andrews Connell's codepen   page (which is ranked high in Google) then stop using that, it is old, it is incorrect.

Current Icons at: https://dev.office.com/fabric#/styles/icons

I keep an eye on Fabric(JS) Icons & Versions myself with my ES6 playground project (so only works in Chrome)
https://365csi.nl/toolkit/iconator.html

**Comment by jbranders** [comment]
Hi Danny,

I don't get it if i use ms-Icon--Pencil i got the Edit icon, but if i use ms-Icon--Edit i get nothing. 
There are icons missing, i'm working with visual studio and nuget package and update to the last version 6.0.0 but if i install only the core nuget package i don't get the components. So i install the nuget package OfficeUIFabric 2.6.3. 

It's strange behavior. 
Do you have suggestion how to update the package? 

Thank you.

**Comment by Danny-Engelman** [comment]
Sorry, I am oldfashioned and in the end always prefer manual over nuget or npm

Back to the version.  
Check what fabric.min.css version you get in the Browser.

Since (at least) 5.0.0 The only icon with Pencil in the name is:  
![](http://i.imgur.com/gfnQISb.jpg)

**Comment by jbranders** [comment]
Hi Danny,

Thank you for the response. I have update the package again and now it's okay. 

Thanks for the support.
