### ISSUE TITLE
Is an Angular2 library going to be available?

### ISSUE THREAD

**Issue by kunshao-msft** [OfficeDev/office-ui-fabric-core#926]

**Comment by mikewheaton** [comment]
Hi @kunshao-msft, the [ngOfficeUIFabric](https://github.com/ngOfficeUIFabric/ng-officeuifabric) project is a community effort outside of Microsoft and I'm not certain of their plans to support Angular 2. Try asking over there and I'm sure they'll be happy to discuss. 😄
