### ISSUE TITLE
Question: Selawik font

### ISSUE THREAD

**Issue by manndave** [OfficeDev/office-ui-fabric-core#927]
First, the support for a less-restrictive font is great, thanks for that.  I'm about to start a major new project and would love to use Fabric but the font issue was a stumbling block before this.

It does raise a question, though.  As I understand it, specifying Selawik (i.e. on the body tag: `ms-Fabric--selewik`) will load "the Selawik web font if Segoe UI is not available locally" (quote from documentation).  Does this mean that Segoe can/will be used if the user already has it installed on their machine, for example via an Office install, and Selawik will only be used if the user does not have Segoe installed?  There is a slight distinction between this and how I've always interpreted the font license.  The wording in the docs seems to imply that we are OK so long as our non-Office/SharePoint app isn't the one to download Segoe to the users machine but that we can use it if it's already there.
Does that make sense?  Is it a correct interpretation?

Thanks,
Dave

**Comment by mikewheaton** [comment]
The [Fabric Assets License](aka.ms/fabric-assets-license) applies only to the assets on the CDN, such as the web font. It doesn't cover the locally-installed copy of Segoe UI that you'll find on most Windows machines or via an Office install. So while usage of the web font is restricted to developing for the Office ecosystem, any developer can use `font-family: 'Segoe UI';` to use the local copy of Segoe UI in their web application. With this in mind, we've kept the local version of Segoe UI in the font stack even when Selawik is used.

**Comment by manndave** [comment]
Excellent.  That's what I hoped/thought might be the case, but wanted to confirm.  

Unrelated, but FYI, my latest course on Fabric is done and should be published on Pluralsight soon.  I cover using Selawik in the course, which is where this question came from.

Thanks.

**Comment by mikewheaton** [comment]
That's great news, @manndave, please let us know when it's published! 🎉
