### ISSUE TITLE
Media Queries broken breakpoints

### ISSUE THREAD

**Issue by frederick-armando** [OfficeDev/office-ui-fabric-core#929]
When manipulating visibility classes (based on media queries) of Fabric Core, for example with `ms-hiddenLgUp` css class. I have noticed that the visibility constraints get violated when resizing my browser window, for some "breakpoints" of the visibility classes. 

Indeed, at precisely 1365px, when decorating div block with `ms-hiddenLgUp` class, the element is supposed to be hidden but it is not. You can access this reproduction case minimal sample to with both 4.1.0 and 6.0.0 version of Fabric Core. See screenshots below. [Fabric_Breakpoint_6.0.0.zip](https://github.com/OfficeDev/office-ui-fabric-core/files/831130/Fabric_Breakpoint_6.0.0.zip)

**At 1365px**
![image](https://cloud.githubusercontent.com/assets/16651802/23754436/417b5dca-04dd-11e7-8b6e-ef4dc836e1f0.png)
![image](https://cloud.githubusercontent.com/assets/16651802/23754454/4fd709a0-04dd-11e7-9f76-a559b1ec2c77.png)
![image](https://cloud.githubusercontent.com/assets/16651802/23754471/5f080294-04dd-11e7-98e1-fdda32851378.png)

**At 1919px**
![image](https://cloud.githubusercontent.com/assets/16651802/23754514/8c193b90-04dd-11e7-8461-4beadc53d8b7.png)
![image](https://cloud.githubusercontent.com/assets/16651802/23754522/953c7200-04dd-11e7-8685-83714c9911e6.png)
![image](https://cloud.githubusercontent.com/assets/16651802/23754533/9ef5ec54-04dd-11e7-80f0-efb0d1940be2.png)

**Comment by mikewheaton** [comment]
I haven't been able to repro this issue. Could you try this [CodePen](https://codepen.io/mikewheaton/pen/wJjMOp?editors=1100) and let me know if you see the problem there?

**Comment by frederick-armando** [comment]
Have you tried the "Toggle device toolbar" into google chrome developer tools ? I was able to reproduce this bug with your pen helped by this tool.
While verifying i have noticed i could only reproduce this issue with chrome (57.0.2987.98), and breakpoints pose no problem with opera, firefox or edge.

![image](https://cloud.githubusercontent.com/assets/16651802/24243347/1af2943c-0fbb-11e7-9e4e-506bc7968777.png)

**Comment by mikewheaton** [comment]
There seems to be something going on with CodePen's editor view that prevents the media queries from applying. If I [change the view to full page](https://codepen.io/mikewheaton/full/wJjMOp/) then everything is working as expected:

![image](https://cloud.githubusercontent.com/assets/1382445/24257487/45218690-0fa8-11e7-984e-4894485a38ca.png)

![image](https://cloud.githubusercontent.com/assets/1382445/24257502/4dd9ff88-0fa8-11e7-8358-e28405efcb06.png)

Is this problem showing up within an app that I could take a closer look at? I'm not sure what could be going wrong here as the media queries are very simple.

**Comment by frederick-armando** [comment]
When i answered you, i used the full page view, so i don't think the problem come from codepen's editor. As you can see in the attachement of my first post, the problem happend without any "interferences". I assume it's mostly chrome's fault (and not only on my computer). You can check on https://app.keluro.com/

At 1366px (normal)
![image](https://cloud.githubusercontent.com/assets/16651802/24303395/19474adc-10b6-11e7-988d-a7b306113e0d.png)

At 1365px (issue: the hamburger menu appear)
![image](https://cloud.githubusercontent.com/assets/16651802/24303415/3603411c-10b6-11e7-8969-18bdb4914d84.png)

I don't know what happened with the media queries but it's a really weird comportement of this class on chrome (not canary) at the breakpoints.

**Comment by mikewheaton** [comment]
At 1365px could you inspect the hamburger element and see what the applied styles are? You should see:

![image](https://cloud.githubusercontent.com/assets/1382445/24314517/3ad41304-109f-11e7-9d61-28df9272a96d.png)

**Comment by mikewheaton** [comment]
I'm going to close this issue for now as I'm not able to get a repro. Please reply back with more details if this continues to be a problem.

**Comment by Katli95** [comment]
I am experiencing the same issue :/ Also using Chrome, Version 59.0.3071.115 (Official Build) (64-bit)

Has there been any progress on the problem? 

Screenshot of codepen, size visible in upper right hand corner:

![image](https://user-images.githubusercontent.com/11443825/28339627-430e4c84-6bfc-11e7-9b92-57aadcd7fbec.png)

**Comment by tom-daly** [comment]
I believe that I am experiencing the same issue. There is a gap where both ms-hiddenMdUp and ms-hiddenSm show 

@media (max-width: 479px)
<style>…</style>
.ms-hiddenLgDown, .ms-hiddenMdDown, .ms-hiddenSm, .ms-hiddenXlDown, .ms-hiddenXxlDown {
    display: none!important;
}

The gap is within the decimal of a pixel. So in chrome I'm measuring 479.091px .... that technically is between 479 < 479.091 < 480... 

This happens at every single other breakpoint when it falls in the decimal of a pixel range. I'm using ms-hiddenMdUp and ms-hiddenSm so I only see it a few times.

media (max-width: 639px) and (min-width: 480px)
<style>…</style>
.ms-hiddenLgDown, .ms-hiddenMd, .ms-hiddenMdDown, .ms-hiddenMdUp, .ms-hiddenXlDown, .ms-hiddenXxlDown {
    display: none!important;
}

![image](https://user-images.githubusercontent.com/9259305/44415773-3bd2e600-a53f-11e8-9d54-8bd10e4ae41b.png)

![image](https://user-images.githubusercontent.com/9259305/44415783-41303080-a53f-11e8-9ae5-dfa196f3872d.png)
