### ISSUE TITLE
2-digit year format in DatePicker defaults to 1900 in Edge

### ISSUE THREAD

**Issue by kopgenorth** [OfficeDev/office-ui-fabric-core#930]
having a date format with a 2-digit year in a DatePicker will change to 19xx on user selection.

**Comment by mikewheaton** [comment]
Hi @kopgenorth, Fabric Core no longer contains components like the DatePicker. Could you file this issue under [Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js/issues) or [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react/issues)? Thanks!

**Comment by kopgenorth** [comment]
Will do, thanks.
