### ISSUE TITLE
Icon request - italic

### ISSUE THREAD

**Issue by lszomoru** [OfficeDev/office-ui-fabric-core#931]
The current icon set contains all the icons for a simple editor toolbar except the icon for "Italic". Could you please add this icon? Thanks! 

Ladislau

**Comment by Jahnp** [comment]
Hi @lszomoru, this should exist right now as of Fabric Core 6.0 with `ms-Icon--Italic`.  I just checked this on the Fabric site here: http://dev.office.com/fabric#/styles/icons

Are you not seeing this in the current set you're using? Which version of Fabric are you on?

**Comment by lszomoru** [comment]
You are correct, my bad. Closing the ticket.
