### ISSUE TITLE
Update to latest MDL2 icon set

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#932]
There is a new release of the MDL2 icon set which contains new icons.

**Comment by Danny-Engelman** [comment]
I see ``https://spoprod-a.akamaihd.net/files/fabric/office-ui-fabric-core/6.0.0/css/fabric.min.css``  
still points to ``https://static2.sharepointonline.com/files/fabric/assets/icons/fabricmdl2icons.woff2``

which, as far as I can tell is still missing

ColumnLeftTwoThirds
ColumnRightTwoThirds
DoubleColumn
OfficeAddinsLogo
PlannerLogo
SingleColumn
Snowflake
TripleColumn

from the list of iconnames in:
``https://raw.githubusercontent.com/OfficeDev/office-ui-fabric-core/master/src/data/icons.json``
