### ISSUE TITLE
onPageAdded callback for DetailsList component

### ISSUE THREAD

**Issue by prashkan90** [OfficeDev/office-ui-fabric-core#939]
The list component has an optional onPageAdded callback for monitoring when a page is added. Our use case involves lists with a large number of items. For better performance, we use this property to implement paging logic. We would like to switch from List to DetailsList since the latter offers resizable column headers and more. However, it looks like there is no property we can use to implement paging. Is this in the pipeline?

**Comment by micahgodbolt** [comment]
Does this belong on Fabric-React or Fabric-JS?

**Comment by prashkan90** [comment]
Fabric-React: https://dev.office.com/fabric#/components/detailslist

**Comment by prashkan90** [comment]
Any updates on this? We've added paging by adding null at the end of our list and using onRenderMissingItem to fetch more items. However, this feels cumbersome and prone to bugs. Adding the onPageAdded option (List) to DetailsList would be very useful.

**Comment by Jahnp** [comment]
Hi @prashkan90, sorry for the delay, but could you re-open this issue there? This repo is for tracking issues related to Fabric Core styles, not the Fabric React components. The devs triaging issues there won't have visibility into this. Thanks!
