### ISSUE TITLE
Contextual menu control should collapse submenus with left arrow

### ISSUE THREAD

**Issue by dasanto** [OfficeDev/office-ui-fabric-core#940]
When focus is in a submenu in a contextual menu, I should be able to press the left arrow to collapse that submenu.

**Comment by micahgodbolt** [comment]
@dasanto is this meant for the React or JS repo?

**Comment by dasanto** [comment]
@micahgodbolt React. Sorry if this is on the wrong repo.

**Comment by mikewheaton** [comment]
Please add this to the [Fabric React issues list](https://github.com/OfficeDev/office-ui-fabric-react/issues). Thanks!
