### ISSUE TITLE
https://dev.office.com/fabric#/styles/icons icons not appearing

### ISSUE THREAD

**Issue by kenhansen01** [OfficeDev/office-ui-fabric-core#942]
When searching for icons on the fabric website, they are not visible. Both in Chrome  v 56.0.2924.87 (64-bit) and IE 11 v 11.0.9600.18617

![image](https://cloud.githubusercontent.com/assets/5445157/24558738/d9c82c68-1601-11e7-9513-4bc8cc73e6cd.png)

**Comment by mikewheaton** [comment]
That's strange, it's working for me:

![image](https://cloud.githubusercontent.com/assets/1382445/24559278/050bb48a-15f3-11e7-8e98-fee4e71530a7.png)

Could you try clearing your cache and reloading the page? We made some updates to the website recently and it's possible that something got mixed up there.

**Comment by kenhansen01** [comment]
Hmm. Clearing the cache, etc. did not help. I thought it might be the firewall (though it wasn't a problem previously), so I tried my phone (Nexus 6 - Chrome browser) on LTE and still no luck. I will try on another device (and connection) when I get home.

**Comment by mikewheaton** [comment]
We've identified some strange caching issues with the site that @battletoilet is working on resolving now. It's possible that I'm the one getting the cached version, and you're seeing the latest. Sorry for the confusion here, we're working on a solution and in the meantime would appreciate any information that helps us repro this.

**Comment by kenhansen01** [comment]
It is appearing now. Closing issue.

![image](https://cloud.githubusercontent.com/assets/5445157/24708661/23ac2e68-19dd-11e7-8690-137be52906c6.png)
