### ISSUE TITLE
2.6.2 & 2.6.3 CSS files are missing from CDN

### ISSUE THREAD

**Issue by andrewconnell** [OfficeDev/office-ui-fabric-core#944]
MDL1 CSS files missing from CDN.

## observed
`GET https://appsforoffice.microsoft.com/fabric/2.6.1/fabric.min.css`
200 OK
`GET https://appsforoffice.microsoft.com/fabric/2.6.2/fabric.min.css`
**404** <<<<<
`GET https://appsforoffice.microsoft.com/fabric/2.6.3/fabric.min.css`
**404** <<<<<

## expected
`GET https://appsforoffice.microsoft.com/fabric/2.6.1/fabric.min.css`
200 OK
`GET https://appsforoffice.microsoft.com/fabric/2.6.2/fabric.min.css`
200 OK
`GET https://appsforoffice.microsoft.com/fabric/2.6.3/fabric.min.css`
200 OK

:(

**Comment by Danny-Engelman** [comment]
Haven't tested older, 

**5.0.1 , 5.1.0 and 6.0.0** are NOT on https://appsforoffice.microsoft.com/fabric/ either

All versions are available on:

* https://spoprod-a.akamaihd.net/files/fabric/office-ui-fabric-core/6.0.0/css/fabric.min.css

and

* https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/6.0.0/css/fabric.min.css

**Comment by mikewheaton** [comment]
Sorry for the oversight here, I'll add them to the CDN right away. As @Danny-Engelman mentioned, the URLs will be the new SharePoint Online CDN, and not AppsForOffice.

**Comment by mikewheaton** [comment]
As @Danny-Engelman mentioned, the CDN we use is now hosted by SharePoint. Here are the URLs you're looking for:

https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/2.6.1/css/fabric.min.css

https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/2.6.2/css/fabric.min.css

https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/2.6.3/css/fabric.min.css
