### ISSUE TITLE
Problem with Panel and Safari scrolling (Mobile) 

### ISSUE THREAD

**Issue by dsimoes** [OfficeDev/office-ui-fabric-core#967]
On our project, with a React Panel component opened, when trying to scroll the panel contents on an Apple mobile device (Safari), scroll will happen on the page under the Panel.

This can actually be replicated on the [Panel demo page ](https://dev.office.com/fabric#/components/panel)

We are currently using:

office-ui-fabric-core: 5.1.0
office-ui-fabric-react: 2.15.0

**Comment by mikewheaton** [comment]
Hi @dsimoes, would you mind opening this issue in the [Fabric React repo](https://github.com/OfficeDev/office-ui-fabric-react)? Thanks!
