### ISSUE TITLE
Aurelia UX support

### ISSUE THREAD

**Issue by LarsKemmann** [OfficeDev/office-ui-fabric-core#968]
It would be *amazing* if you could support the Aurelia framework and especially [Aurelia UX](https://github.com/aurelia/ux). I'm really interested in this. What would it take to add basic support? Is this something you'd consider doing?

(Or if not, would you be able to provide guidance to someone who's sufficiently motivated? :))

**Comment by mikewheaton** [comment]
We're not likely to be able to fund this ourselves, but we encourage and promote community projects such as [ngOfficeUIFabric](http://dev.office.com/fabric#/angular-js). If there are any questions about the colors, fonts, icons, etc. that come up we'd be happy to help, and we'd consider PRs into Core that make it easier to consume for your project. Let us know how we can help.

**Comment by LarsKemmann** [comment]
Thanks @mikewheaton -- will do!

**Comment by mikewheaton** [comment]
I'll close this for now, as there's no action item on our end. Feel free to open issues whenever you have questions, or to reach out to us via [Twitter](https://twitter.com/officeuifabric).

**Comment by danielmeza** [comment]
Hi @LarsKemmann  any update on this? do you have starter to with the repo, I would like to contribute!

**Comment by LarsKemmann** [comment]
@danielmeza Hey, sorry that I took so long to reply. I'm taking a different approach at the moment, focusing on (framework-agnostic) Web Components. Those _should_ play well with Aurelia, but I'm still too early in the process to really be looking at the UI Fabric styles/behavior/etc.

**Comment by LarsKemmann** [comment]
@danielmeza That being said... I just saw your experimental repo & that is a _really_ interesting idea. :)
