### ISSUE TITLE
Remove Third Party Notices

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#970]
This project contains a [Third Party Notices](https://github.com/OfficeDev/office-ui-fabric-core/blob/master/Third%20Party%20Notices.txt) file that covers Pickadate, JEANS, and jQuery Easing. These are all part of Fabric JS but are not in Fabric Core, so the notice can be removed.

**Comment by Jahnp** [comment]
Closed via #971
