### ISSUE TITLE
Request new icons inspired by Office.js api

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-ui-fabric-core#972]
In Word with office.js you can insert or export different file formats like text, ooxml or html. It would be cool to have some icons for that. 

ms-Icon--Text (also possible to separate in PlainText and RichText)
ms-Icon--Html
ms-Icon--Xml or ms-Icon--Ooxml

**Comment by mikewheaton** [comment]
These might not be exactly what you're looking for, but "TextDocument", "FileHTML", and "FileCode" may be suitable for your needs:

![image](https://user-images.githubusercontent.com/1382445/29421862-3a7b725e-832b-11e7-82a7-db2443319d45.png)
