### ISSUE TITLE
Fabric UI and JSLink

### ISSUE THREAD

**Issue by emaV** [OfficeDev/office-ui-fabric-core#974]
As we are working on customization of Sharepoint 2013 form with JSLink we're wondering if and how Fabric UI (core or js) fit with the model.

There a number of Sharepoint objects you can attach JSLink to modify presentation/behaviuor:

- Site Columns
- Content Types
- List Views
- List Forms (e.g. New / Edit / Display forms)
- List View Web Parts
- List Form Web Parts

Is Fabric UI intended to be used with such customizations?

**Comment by Danny-Engelman** [comment]
Fabric is a CSS library like Bootstrap or Googles Material
and can be used for any Front-End application

So it can be used for SharePoints CSR (Client Side Rendering) 
JSLink is only the technology to link JS files, CSR can be applied without

JSLink can not load CSS files, so you have to load Fabric with JS (or as LINK in an ASPX file)
