### ISSUE TITLE
Using Office UI Fabric for Desktop Applications

### ISSUE THREAD

**Issue by adaoust** [OfficeDev/office-ui-fabric-core#976]
My understanding of the answers in the #123 and #341 issues is that the Office UI Fabric has to be used for Office Add-Ins exclusively (or maybe anything that enhances Office User Experience?). However, I feel like the following scenario hasn't been considered.

We created a SharePoint SPFX Web-Part using the Office UI Fabric that calls some web service to operate on items. One of our clients asks for a desktop application that performs the same operations. Our first thought was to use something like [Electron](https://electron.atom.io/) and port over our UI from that Web-Part to give those users the exact same experience. However, I feel like this is prohibited by the license.

Can we get clarification as to what is allowed and what isn't?

Also, if there is absolutely no options for desktop applications what would be an alternative? 

Thanks,

Alex

**Comment by mikewheaton** [comment]
To be clear, I'm not a lawyer and my interpretation of the license is as good as yours.

The [license](https://static2.sharepointonline.com/files/fabric/assets/license.txt) states that the assets (such as the Segoe UI font and icon font) can be used "for the purpose of developing for Office and other Office 365 endpoints including, but **not limited to**, Office Add-ins, SharePoint Web Parts, SharePoint Apps, and Custom Office 365 apps" (emphasis mine).

Does this app tie into SharePoint services or anything else in the Office ecosystem? When someone is using it, do they get that it's another way of interacting with that web part? Again, I'm not a lawyer, but my understanding is that it's intended to cover anything even loosely related to Office.

To be completely safe, you could substitute your font and icons, as the rest of the project is completely open source under an MIT license. But I suspect that your usage would be fine if this is a companion app/view to an existing web part. I hope that helps.
