### ISSUE TITLE
Fabric Icons, technology for distributing only required icons?

### ISSUE THREAD

**Issue by Danny-Engelman** [OfficeDev/office-ui-fabric-core#978]
https://raw.githubusercontent.com/OfficeDev/office-ui-fabric-core/master/src/data/icons.json

I see the number of icons increased again, from 874 to now 977

For Mobile every byte still counts

Is there any development planned for distributing only the used icons?

**Comment by mikewheaton** [comment]
There sure is! We're working on an icon subsetter, which will allow you to select the specific icons your application needs rather than requesting the full set. Right now we're getting this set up for internal projects and we hope to be able to share it externally after that.
