### ISSUE TITLE
Fix documentation of Responsive Layout grid column name variables

### ISSUE THREAD

**Issue by ultrawebsites** [OfficeDev/office-ui-fabric-core#979]
The column naming was changed to remove the 'u' prefix from the Layout grid columns, as per https://github.com/OfficeDev/office-ui-fabric-core/commit/d86bdd0a9445a82e4e074be40a38da69c55459eb

However, the documentation at http://dev.office.com/fabric#/styles/layout still refers to the variables with the 'u' prefix.

**Comment by Jahnp** [comment]
Hey @ultrawebsites , so sorry for the delay on following up on this! This has been resolved on the website--closing for now.
