### ISSUE TITLE
Testing (Client Side) if Fabric is ^6.0.0

### ISSUE THREAD

**Issue by Danny-Engelman** [OfficeDev/office-ui-fabric-core#983]
Have had some clients who were using the ``-u-`` classnames with a newer Fabric version

What would be the shortest JS way for testing if the loaded Fabric Core version is 6.0.0 (or higher)?

I know we can dig into ``document.stylesheets``; wonder if something shorter is available

Or can it maybe be done with CSS only?

**Comment by mikewheaton** [comment]
In your build system you could inspect `package.json`. Once it's built and running in the browser, I think you'd want to dig in to `fabric.css` and look at the top comments, which take the form:

```
/* Copyright (c) Microsoft. All rights reserved. Licensed under the MIT license. See LICENSE in the project root for license information. */
/**
 * Office UI Fabric Core 7.0.0
 * The front-end framework for building experiences for Office 365.
 **/
```

You could also try using one of the classes on an element and then inspect the applied styles to see if it's present or not.
