### ISSUE TITLE
how to use npm office-ui-fabric-core

### ISSUE THREAD

**Issue by ashutosh1211** [OfficeDev/office-ui-fabric-core#984]
Hi I want to use office-ui-fabric-core css in react components and include only required css from office-ui-fabric-core. at build time.

**Comment by mikewheaton** [comment]
When you use NPM to get Fabric Core, the file you are looking for is `dist/sass/_References.scss`:

![image](https://user-images.githubusercontent.com/1382445/27352571-f7cbd2b6-55b5-11e7-9f8f-3128e6b40e83.png)

You can import this into your own SCSS file, which will give you access to all of the variables and mixins in Fabric Core. For example:

```
@import '../path/to/dist/sass/_References';

.myComponent {
  background-color: $ms-color-darkRed;
  color: $ms-color-white;
}
```

**Comment by ashutosh1211** [comment]
@mikewheaton thanks ✌️😀
