### ISSUE TITLE
Icons don't load on a Windows Server 2016 machine

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/office-ui-fabric-core#987]
See the rendering of the Fabric site, for example:

![fabric icons](https://cloud.githubusercontent.com/assets/2230453/26808362/f0075100-4a10-11e7-891d-2d75b3266d61.png)

The machine is a Windows Server 2016 machine.  The site displays fine in Firefox, only IE has this issue.  Other parts of the site (and other sites) load fine, it's just the Fabric icons that seem to have a problem.

**Comment by Zlatkovsky** [comment]
I have an F12 capture as well, please see attached.
[Fabric icons network capture.zip](https://github.com/OfficeDev/office-ui-fabric-core/files/1053490/Fabric.icons.network.capture.zip)

**Comment by mikewheaton** [comment]
I'm not sure how to open the `.har` file from the network capture. Can you open the developer tools and see whether the web font is being downloaded from the CDN? I suspect that the font is being blocked by a security policy or something.

**Comment by Zlatkovsky** [comment]
The `.har` file can be imported into Fiddler (`File -> Import Session -> HTTP Archive`), or a tool like https://chrome.google.com/webstore/detail/http-archive-viewer/ebbdbdmhegaoooipfnjikefdpeoaidml?hl=en

Screenshot is below:

![image](https://user-images.githubusercontent.com/2230453/26846972-42a77288-4ab0-11e7-9f6d-df6e21c4b76a.png)

**Comment by Danny-Engelman** [comment]
Which version of IE are you using?
And does it happen with Edge too?

If you goto:  https://365csi.nl/toolkit/iconator/index.html

Do you see that Abc icon on the right?

*You won't see the rest of the page, it uses plain ES6 which only a modern Browser understands*

![](http://i.imgur.com/Nh6C7tY.jpg)

**Comment by Zlatkovsky** [comment]
Let me ask the person who had originally reported this to me reply to this thread directly -- and she'll be able to answer your questions.

Thanks!

**Comment by zefangtang** [comment]
Hi, I'm the person with the issue. This is on Internet Explorer 11 (11.1198.14393.0, update version 11.0.42). The Abc icon does not appear.
![image](https://user-images.githubusercontent.com/12416018/26891607-7b70c172-4b6a-11e7-9bb2-9c11e47dee98.png)

**Comment by Danny-Engelman** [comment]
Check F12 Network tab, what is the full URI to  fabric.css, and is there an error?

**Comment by zefangtang** [comment]
https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/5.1.0/css/fabric.min.css
No error as far as I can tell.
![image](https://user-images.githubusercontent.com/12416018/26893248-a640e616-4b6f-11e7-9cf8-afe18720908d.png)

**Comment by mikewheaton** [comment]
So there's no request for the icon font (should be a `.woff` or `.woff2` file) here at all?

**Comment by zefangtang** [comment]
There doesn't appear to be.

**Comment by mikewheaton** [comment]
Could you check if the feature to 'block untrusted fonts' is enabled? See [this article](https://docs.microsoft.com/en-us/windows/threat-protection/block-untrusted-fonts-in-enterprise). If you use Outlook's web app or try a site like [Font Awesome](http://fontawesome.io/), do the icons show there?

**Comment by zefangtang** [comment]
That didn't work, but it gave me the idea of checking my IE security settings. Turns out the issue was that font download was disabled. Enabling it fixed the issue! Thanks!

**Comment by mikewheaton** [comment]
Good to hear!

**Comment by Zlatkovsky** [comment]
@zefangtang , would you mind pasting a screenshot of where you found the setting -- so that if folks stumble into this in the future, they know where to look?

@mikewheaton , is this something that could be programmatically detected?  I.e., is there a way that, on loading, the program could check if it indeed was able to display the icons?  Our interface is very icon-driven, and so when some of the important ones go missing, the program becomes unusable (and it's unclear to the user what is even expected of him/her)...

**Comment by mikewheaton** [comment]
This [answer on StackOverflow](https://stackoverflow.com/questions/5680013/how-to-be-notified-once-a-web-font-has-loaded) could be a place to start. I'm not familiar with the CSS font loading API, but there should be a way to detect when fonts load and compare that to the expected result.

**Comment by zefangtang** [comment]
Sure. Internet options > Security > Custom level.
![image](https://user-images.githubusercontent.com/12416018/27108195-ae02569c-5050-11e7-88d7-5327bb6a904c.png)

**Comment by Zlatkovsky** [comment]
Clarifying comment:  the relevant part in the above image is the `Downloads => Font downloads => Enable` radio button.
