### ISSUE TITLE
Can't override Pivot and PivotItem styles with styled-components

### ISSUE THREAD

**Issue by BrandoIsNotASword** [OfficeDev/office-ui-fabric-core#997]
Apparently there is no a direct way to override the styles of these components. There is no a prop for styling and also the className prop is completely ignored. I'm using React.

Any suggestions?

**Comment by Jahnp** [comment]
Hey @BrandoIsNotASword, so sorry for the delay here. It looks like this is meant for [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react), not Fabric Core (this repo). If that's the case, would you mind re-opening this issue there? I'll go ahead and close this one in the meantime. Thanks!
