### ISSUE TITLE
Collapse GroupedList / DetailsList by Default

### ISSUE THREAD

**Issue by ThatCarterMcBride** [OfficeDev/office-ui-fabric-core#999]
Hello people

Is there a way to have the groups in GroupedList / DetailsList collapsed upon mounting?

It doesn't seem like there are any available public methods to call on any of the components in the mounting cycle, and changing the `isAllGroupsCollapsed` in `groupProps` affects this?

Thank you for your time.

EDIT: This is probably better placed in the [React implementation](https://github.com/OfficeDev/office-ui-fabric-react), not the core. Sorry! 😕 [I have submitted a question there.](https://github.com/OfficeDev/office-ui-fabric-react/issues/2176)

**Comment by Jahnp** [comment]
Whoa--sorry for the delay here @ThatCarterMcBride. Thanks for opening this issue in the React repo. I'll go ahead and close this one in the meantime.
